### ISSUE TITLE
Separate validation from conversion to model type

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#101]
Validation is very slow, and need not happen every time one wishes to create code.

Kim and I have worked up a modification of `es:model-from-node` that provides for this optimization and clarification.

This task is an open issue to set down the proposed change and circulate.

It is labeled a bug because it manifests as a peculiar usability issue in JavaScript.

**Comment by grechaw** [comment]
We are considering this change as a candidate for EA-3 so that we do not have a lingering design change after EA-3.  We've analyzed the blast radius and QA is on board.  I need to talk with WG and @jmakeig tomorrow to make sure we can move forward.

**Comment by bsrikan** [comment]
Tests updated. Issue will be shipped after successful regression run on 08/19.

**Comment by bsrikan** [comment]
Tests are running successfully in regression. Shipping the bug.
