### ISSUE TITLE
Task to update tests per #109

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#110]
Task to update test for changes in PR #109 involving design changes to validation. APIs involved

model-from-node() -- this is removed now
model-validate() -- validation of model doc. o/p is a model
model-from-xml($xml) -- converts from xml doc to a model
model-to-json/xml -- no changes/impact

**Comment by grechaw** [comment]
I also took out model-to-json as it is a no-op

**Comment by bsrikan** [comment]
Tests updated to incorporate model-validate() and model-from-xml() as appropriate wherever model-from-node() was being used earlier.
#111 also includes some cleanup to tests since model-to-json() is removed.

Will ship this task after tomorrow's clean regression run

**Comment by bsrikan** [comment]
Shipping the task. Tests are running successfully in regression.
