### ISSUE TITLE
Type versioning

### ISSUE THREAD

**Issue by jmakeig** [marklogic/entity-services#113]
Demonstrate how version an entity type definition and write a translation from old to new.

Bonus: Add bitemp to be able to query on old or new versions as they were known previously.

**Comment by grechaw** [comment]
Made good progress on this eaxmple today.  Setting to fix as I'm now in progress.  The example I'm working on first is a minimal data migration project, where the delta between the models is very small.

**Comment by grechaw** [comment]
In PR

**Comment by bsrikan** [comment]
Versions example look good. 
@jmakeig Please let me know if I can ship this task or you want to take a look and ship yourself since its your recipe.

**Comment by bsrikan** [comment]
Shipping this task!
