### ISSUE TITLE
Getting 401: Unauthorized error while running examples in reg machine

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#119]
```
:entity-services-examples:mlDeleteModuleTimestampsFile
:entity-services-examples:mlPrepareRestApiDependencies
:entity-services-examples:mlDeployApp
GET request for "http://localhost:8002/manage/v2/databases" resulted in 401 (Unauthorized); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":   {"statusCode":401,
   "status":"Unauthorized",
   "message":"401 Unauthorized"
  }
}
:entity-services-examples:mlDeployApp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':entity-services-examples:mlDeployApp'.
> 401 Unauthorized
```

@grechaw as discussed assigned issue to @jmakeig

**Comment by jmakeig** [comment]
@bsrikan Can you verify that the users (`adam` and `whitney`) and the roles (`race-*`) were created successfully? Did you update `application.properties`, starting with `application.properties.CHANGEME`?

**Comment by bsrikan** [comment]
@jmakeig I updated application.properties.CHANGEME so the projectDir points to where entity-services-examples is located.
Ran mldeploy after this edit(both by keeping filename as is and by removing CHANGEME) and still got the 401 issue; users and roles werent created.

**Comment by grechaw** [comment]
Thanks @bsrikan that makes sense to me now.  mldeploy has to not only run but also to work.

**Comment by bsrikan** [comment]
@grechaw So it seems now that this issue was caused by #85. I updated the build script and now examples project is deployed from examples folder. Dont see the 401 error anymore. Shipping it.

**Comment by grechaw** [comment]
cool
