### ISSUE TITLE
Namespaces for enveloped entity instances

### ISSUE THREAD

**Issue by jmakeig** [marklogic/entity-services#122]
Generally it's best practice to put all elements from a vocabulary in their own namespace to avoid conflicts and to allow easy and unambiguous discrimination from elements in other vocabularies (e.g. for schema validation). On the other hand, namespaces add complexity for just about everything downstream. What’s the cost-benefit? Should this be optional? If so, how do we determine the namespace URI and prefix?

**Comment by grechaw** [comment]
"If so, how do we determine the namespace URI and prefix?"

We have included baseUri in the model for this purpose (for the URI anyhow).  There are potentially two uses for this Uri in instance data: both in the XML persistence layer and in a TDE template to extract triples.

**Comment by paxtonhare** [comment]
I too would like to see support for namespaces in instances.

**Comment by grechaw** [comment]
temporarily switched to 'task' to prod the bugtrack integration into setting to 9.0-2.
still considered enhancement until we decide to put it into a scope of work tho.

**Comment by grechaw** [comment]
Set milestone and labels for BT update

**Comment by grechaw** [comment]
Considering design for namespaces in canonical documents.
We already have a "baseURI" property, which is used to form the left-hand side of triples.  It would be a natural fit for also being the namespace of canonical instances, but there are other options that would provide more flexibility.

Say each entity type could take a "namespace" property.  Then the canonical XML namespace would be controlled at the type level, not the model/vocabulary level.  Would that be preferable?

Curious about opinions from @paxtonhare , @jmakeig 


``
  {"info":
     {"title":"Socks", "version":"3.0.0", "baseUri": "http://example.ontology/clothing/"} 
   "definitions":
        {
          "sock" : {
               "namespace":"http://example.org/clothing/sock"
        }
  }
```

This approach would ensure granularity for validation purposes, but make a lot more namespaces, which might not be good XSD convention.

**Comment by grechaw** [comment]
implemented changes to database properties creation and search options.  schema looks perhaps more complex than I thought, test instances are done.

**Comment by bsrikan** [comment]
Added tests that will be in PR later today.

**Comment by bsrikan** [comment]
Task completed. Added tests are running fine. Shipping the task
