### ISSUE TITLE
401 error on 'gradle mlDeploy

### ISSUE THREAD

**Issue by sammefford** [marklogic/entity-services#123]
I'm trying to follow the instructions from README.md, and I'm getting the following:

```
$ gradle mlDeploy
:mlDeleteModuleTimestampsFile
:mlPrepareRestApiDependencies
:mlDeployApp
:mlPostDeploy UP-TO-DATE
:mlDeploy
:entity-services:mlDeleteModuleTimestampsFile
:entity-services:mlPrepareRestApiDependencies
:entity-services:mlDeployApp
:entity-services:mlPostDeploy UP-TO-DATE
:entity-services:mlDeploy
:entity-services-e2e:mlDeleteModuleTimestampsFile
:entity-services-e2e:mlPrepareRestApiDependencies
:entity-services-e2e:mlDeployApp
:entity-services-e2e:mlPostDeploy UP-TO-DATE
:entity-services-e2e:mlDeploy
:entity-services-examples:mlDeleteModuleTimestampsFile
:entity-services-examples:mlPrepareRestApiDependencies
:entity-services-examples:mlDeployApp
GET request for "http://localhost:8002/manage/v2/databases" resulted in 401 (Unauthorized); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":   {"statusCode":401,
   "status":"Unauthorized",
   "message":"401 Unauthorized"
  }
}
:entity-services-examples:mlDeployApp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':entity-services-examples:mlDeployApp'.
> 401 Unauthorized
```

**Comment by sammefford** [comment]
should I be added to the project so I can set assignee and labels?

**Comment by grechaw** [comment]
It's true, the examples no longer deploy from the top-level directory.
To use examples, first `cd` into the examples directory then run

`../gradlew mlDeploy`

and it will properly deploy the users for the examples.

**Comment by grechaw** [comment]
Added team-java write access to this repo.

**Comment by sammefford** [comment]
When I did that, I got the following:

```
$ gradle mlDeploy
:entity-services-examples:mlDeleteModuleTimestampsFile
:entity-services-examples:mlPrepareRestApiDependencies
:entity-services-examples:mlDeployApp
POST request for "http://localhost:8002/v1/rest-apis" resulted in 400 (Bad Request); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":400, "status":"Bad Request", "messageCode":"RESTAPI-INVALIDCONTENT", "message":"Your bootstrap payload caused the server to throw an error.  Underlying error message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Port 8203 is in use."}}
:entity-services-examples:mlDeployApp FAILED
```

Might that mean that I'm already setup and ready to go?  Does mlGradle not have a way to run everything idempotent?

**Comment by grechaw** [comment]
I have not seen this before.  The deploy normally is idempotent.  My guess is that gradle's internal dependency (stored relative to your current directory) stores what has been run and not.
So my guess is that either you'll just see this message once, or this error will generally go away if you `gradle mlUndeploy` first.

Note that @jmakeig introduced a required manual step in the examples last week.

But his change, I think, would not produce the error that you see above.

**Comment by sammefford** [comment]
What's the required manual step?

Also, how do I get the transforms installed?  I tried 

    gradle entity-services-examples:run

and I got the errors: "transform extension does not exist: turtle-to-xml", "transform extension does not exist: ingester" and "transform extension does not exist: ingester-angel-island" and

**Comment by grechaw** [comment]
mlDeploy does need to complete successfully.  It installs all of the extensions.
Sorry there's so much trouble with this stuff!
To get the security of the loader set up, you need to edit

`src/main/resources/application.properties.CHANGEME` 
and save it at `src/main/application.properties`

Probably a better approach would be to supply the project dir from a shell script using a -P gradle property to set it or something.  Maybe this thread can lead to an improvement that will cut through some of this stuff.

**Comment by grechaw** [comment]
Seems the README still needs a makeover...  I'll make a task for that now.

**Comment by jmakeig** [comment]
> you need to edit `src/main/resources/application.properties.CHANGEME`
and save it at `src/main/application.properties`

Is there no way we can figure out the `projectDir` path at runtime? This would eliminate the need for `.CHANGEME` as the other values have sensible defaults.

**Comment by grechaw** [comment]
We can, I'm sure of it.  A shell script could set a gradle property.

We could also put the sample data into the classpath and load it from there.  That would make the project less realistic IMO, but it would work more effortlessly out of the box.

I'll consider a few options here and  find a way forward

**Comment by sammefford** [comment]
I ran 'gradle mlUndeploy' successfully from the entity-services-examples directory, but then trying 'gradle mlDeploy' from that directory gave the same error.  It appears I'm facing a conflict on port 8203 because both e2e and examples are configured to the same port.

**Comment by grechaw** [comment]
Ah, I think @bsrikan is working on that.

**Comment by grechaw** [comment]
I've got a fix whereby application.properties is checked in, and one need not configure the project dir.
I'll make a PR that addresses this issue and some others too.

**Comment by bsrikan** [comment]
PR #128 takes care of the 400 Bad request error resulting from e2e and examples running from same port.
