### ISSUE TITLE
gradle mlUndeploy throws 503

### ISSUE THREAD

**Issue by sammefford** [marklogic/entity-services#126]
from the root entity-services folder:

```
$ gradle mlUndeploy
:mlUndeployApp
GET request for "http://localhost:8001/admin/v1/timestamp" resulted in 503 (Service Unavailable -- Restarting to reload configuration files.); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":
  {"statusCode":503,
   "status":"Service Unavailable -- Restarting to reload configuration files.",
   "message":"503 Service Unavailable"
,   "messageDetail":{
      "messageTitle":"Restarting to reload configuration files."
    }
   }
}
:mlPostUndeploy UP-TO-DATE
:mlUndeploy
:entity-services:mlUndeployApp
:entity-services:mlPostUndeploy UP-TO-DATE
:entity-services:mlUndeploy
:entity-services-e2e:mlUndeployApp
GET request for "http://localhost:8001/admin/v1/timestamp" resulted in 503 (Service Unavailable -- Restarting to reload configuration files.); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":
  {"statusCode":503,
   "status":"Service Unavailable -- Restarting to reload configuration files.",
   "message":"503 Service Unavailable"
,   "messageDetail":{
      "messageTitle":"Restarting to reload configuration files."
    }
   }
}
:entity-services-e2e:mlPostUndeploy UP-TO-DATE
:entity-services-e2e:mlUndeploy
:entity-services-examples:mlUndeployApp
:entity-services-examples:mlPostUndeploy UP-TO-DATE
:entity-services-examples:mlUndeploy
:entity-services-functionaltests:mlUndeployApp
:entity-services-functionaltests:mlPostUndeploy UP-TO-DATE
:entity-services-functionaltests:mlUndeploy
```

**Comment by grechaw** [comment]
Hi Sam, this is expected behavior from ml-gradle when it removes appservers, and marklogic restarts.

**Comment by grechaw** [comment]
Not sure what to do with such issues -- just close or assign back.  i chose the latter here

**Comment by sammefford** [comment]
Hmm, this doesn't look good to me.  Is there an issue logged against ml-gradle?  If not, I can log one.

**Comment by grechaw** [comment]
It's not an issue.  ml-gradle polls the server during restart to see it its come back up yet.  503 is when it's not available.  ml-gradle handles that by trying again a bit later.

**Comment by sammefford** [comment]
If it's not an issue, can we remove the error and stack trace?  Maybe it's just me, but when I see a stack trace I immediately think something went wrong.

**Comment by sammefford** [comment]
Lol, I just looked again and it's not a stack trace.  Sorry about that.  It's a structured JSON error message.  But it stands out, of course.  So I guess my question is whether we can hide it if it's not an issue.

**Comment by kcoleman-marklogic** [comment]
My experience with our gradle projects is that it spews out too much when there's not a problem, and not nearly enough when there is one. It can be quite confusing and frustrating at times.

**Comment by rjrudin** [comment]
I'll file a ticket for this in ml-app-deployer. It logs every HTTP response error that it receives from the Management API. It just needs to be a little smarter to say - if this is a 503 from /admin/v1/timestamp, just ignore it.

**Comment by grechaw** [comment]
@sammefford ok to move this bug to closed?  I don't want to take on hiding messages just in examples code.

**Comment by sammefford** [comment]
I'm fine with closing this, looks like Rob marked it fixed in ml-app-deployer https://github.com/rjrudin/ml-app-deployer/issues/113

**Comment by rjrudin** [comment]
It'll be part of ml-gradle 2.4.0
