### ISSUE TITLE
Complete version translation example.

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#134]
This example code is in progress, but still not complete, so I want a task to identify the work still to do before EA-3.

**Comment by grechaw** [comment]
This is task from the PR you merged yesterday.   We can chat about the version translation.  It could be I should have a more involved example than I do now, but I made a good first pass at a working one.

**Comment by bsrikan** [comment]
Will take a look at it.

**Comment by bsrikan** [comment]
Good to see the results. You are right about having an involved example. SKOS is new to me and it would be great to have a 1:1 on that subject with you to get me initiated.
Assigning back to you @grechaw as there is some more examples to add
