### ISSUE TITLE
Calling CodeGenerator and CSVLoader from ExamplesLoader.java

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#138]
Hi @grechaw ,

I see that you are calling CodeGenerator(viz generator.generate()) & CSVLoader(viz integrator.go()) in ExamplesLoader.java. 

Do you still need to have a main() in CodeGenerator.java & CSVLoader.java with same call.

**Comment by grechaw** [comment]
Not needed to run the examples -- I thought however it might be nice to have an independent method to run those classes.  In particular, CodeGenerator would normally be run separately from a loading process.

I should make a comment to this effect somewhere
