### ISSUE TITLE
version-translator should have informative section listing non-functional differences.

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#139]
report section on non-functional differences in `version-translaror-generate`

While version tranlsator provides code stubs to convert one kind of model to another, it could also include a report section in a comment that describes each model so that one can get an overview of the changes.

This issue was migrated from bugtrack, and there was a subask of 36574.

**Comment by grechaw** [comment]
Here is an example of the output that I've created in my work today, @bsrikan, @jmakeig @kcoleman-marklogic 

```
Type ETOne: 
    primaryKey: pk, ( in source: pk )
    required: p1, p2, ( in source: p1, p2 )
    range indexes: p3, p4, ( in source: p3, p4 )
    word lexicons: p2, ( in source: p2 )
 
 Type ETTwo: 
    primaryKey: pk, ( in source: pk )
    required: p7, p9, p10, p12, ( in source: p8, p9 )
    range indexes: p8, p9, ( in source: p8 )
    word lexicons: p9, ( in source: p7 )
 
 Type ETThree: 
    missing from source model.
    primaryKey: None
    required: None
    range indexes: None
    word lexicons: None
 
 Type ETFour: 
    Removed Type
```

**Comment by grechaw** [comment]
In PR

**Comment by bsrikan** [comment]
Tested and looks good so far. Will test for other version-translator bugs, verify the listing of non-functional differences in other model descriptors and ship the bug.

**Comment by bsrikan** [comment]
For scenario where Source has
```
indexes for Order:
         "primaryKey":"CustomerID",
         "required": [ "CustomerID" ],
         "rangeIndex": [ "CustomerID", "OrderDate" ],
         "wordLexicon": [ "CustomerID", "OrderDate" ]

indexes for OrderDetail:
         "primaryKey": "ProductID"
```
Target has

```
indexes for Order:
         "primaryKey":"CustomerID"
         "required": [ "CustomerID" ],
         "wordLexicon": [ "CustomerID" ]

indexes for OrderDetail:
         "primaryKey": "ProductID",
         "required": [ "ProductID" ],
         "rangeIndex": [ "ProductID", "Quantity" ],
         "wordLexicon": [ "ProductID", "Quantity" ]
```

Target Model report looks like below:

```
 Type Order: 
    primaryKey: CustomerID, ( in source: CustomerID )
    required: CustomerID, ( in source: CustomerID )
    range indexes: None
    word lexicons: CustomerID, ( in source: CustomerID, OrderDate )
 
 Type OrderDetail: 
    primaryKey: ProductID, ( in source: ProductID )
    required: ProductID, ( in source: None )
    range indexes: ProductID, Quantity, ( in source: None )
    word lexicons: ProductID, Quantity, ( in source: None )
```
Type Order:
When Target has None, report doesnt show what was in source. It does so when Target has atleast one property like in wordLexicon. 
Type OrderDetail:
The reverse works just fine when source has None and Target has some index properties:

**Comment by grechaw** [comment]
OK I understand the gap here.  Will get bugfix prepared.

**Comment by grechaw** [comment]
I've got this fix in place.  Running tests and adjusting keys.

**Comment by grechaw** [comment]
should be pretty easy to verify this one.  easier than my next PR :+1:

**Comment by bsrikan** [comment]
Shipping the task. The report in the info section looks good and updated keys are in PR #213.
