### ISSUE TITLE
Add the option to persist Entity Instances as JSON

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/entity-services#144]
Currently entity instances are persisted as XML. The Data Hub Framework gives users the option to persist as XML or JSON. We would like to see this feature added to Entity Services too.

**Comment by jmakeig** [comment]
@grechaw Let’s figure out how this might shake out and how it prioritizes with other stuff on the plates of dev, QA, and docs. We should do it. I just don't know where it fits in terms of size and timing.

**Comment by grechaw** [comment]
One way we could do this:

ad

```
es:instance-to-canonical-json($instance)
es:instance-to-envelope($instance, "json")
```

**Comment by jmakeig** [comment]
Let’s start with a sketch of the the dev, QA, and docs scope. On the face of it, it sounds too big for 9.0-1.

**Comment by grechaw** [comment]
This issue is very important for an early decision.  Justin will consider this issue among the others, and see whether or not it is containable.

**Comment by DavidGorbet** [comment]
I can't believe we didn't consider and scope this out early in the project. Has anything changed since then?

**Comment by jmakeig** [comment]
This was an intentional decision. We knew we'd want to support JSON eventually, but wanted to go deep on the use cases first and then broaden outside of that core. We've received feedback that JSON is important. This is the process of beginning to prioritize that among the other things in 9.0-1.

**Comment by DavidGorbet** [comment]
Do you mean prioritizing feedback for 9.0-2, or did you really mean 9.0-1?

**Comment by jmakeig** [comment]
Probably 9.0-2 given what else we have in 9.0-1. But that's the assessment we need to do. Given the feedback, is this more important than the other stuff already scheduled for 9.0-1 and will it not introduce risk we can't accommodate?

**Comment by grechaw** [comment]
@DavidGorbet You're right in that we did indeed cut this scope early on.  Paxton is voting for it as an important enhancement, so we gave it a good look.  I submit that @paxtonhare design a JSON envelope and implement the functions for it within the data hub.  I suspect the design will be straightforward and we will be able to incorporate his work into a future iteration of Entity Services.

**Comment by DavidGorbet** [comment]
Ok let's make sure this comes up in the Program Review. Thx.

**Comment by grechaw** [comment]
This enhancement is covered now by issue #291
