### ISSUE TITLE
extract-array does not extract a sequence below a property

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#149]
Use Northwind-0.0.1.xqy.

extract-instance-Order shoudl work out of the box for northwind data.  Example, 

/MarkLogic/git/entity-services/entity-services-e2e/data/northwind/orders/10249.xml

It looks as though extract-array needs a /\* on the end of its last line, but we need to verify and test this hypothesis

**Comment by grechaw** [comment]
getting a start on this one.

**Comment by grechaw** [comment]
This is turning out to be a much thornier issue than expected.  I've created several good tests though, and now it's just a matter of getting the code to work!

**Comment by bsrikan** [comment]
Good to know Charles. I am ready for it :)

**Comment by grechaw** [comment]
Collecting work and more information under issue #76 .  I'll reference this bug and that task as part of the PR documentation.

**Comment by bsrikan** [comment]
The fix provided in #167 only works for external references. For local $ref I get an error as below:

`XDMP-AS: (err:XPTY0004) $source as node()? -- Invalid coercion: (fn:doc("10249.xml")/Order/OrderDetails/OrderDetail[1]/ProductID, fn:doc("10249.xml")/Order/OrderDetails/OrderDetail[2]/ProductID) as node()?`


IMO in the entity-services-codegen.xqy code below both local and external $ref should be set to `$wrap-if-array($path-to-property, $extract-reference-fn, false())`
```
let $value :=
 if (empty($ref))
   then
      $wrap-if-array($path-to-property, $casting-function-name, true())
    else
      if (contains($ref, "#/definitions"))
      then
        $wrap-if-array($path-to-property, concat($prefix, ":extract-instance-", $ref-name), true())
      else
        $wrap-if-array($path-to-property, $extract-reference-fn, false())
```

Please investigate @grechaw 
Tested with following ET docs: "valid-ref-same-document.json", "valid-ref-combo-sameDocument-subIri.json"

**Comment by bsrikan** [comment]
I get that error while executing:

ext:instance-to-envelope(ext:extract-instance-Order( doc('10249.xml')))

**Comment by grechaw** [comment]
That does look like the right change.  I must not have a unit test that covers it.

**Comment by grechaw** [comment]
OK I was able to track this down...  With that document and the generated code, I indeed get the error that you do.  It's indicative of an XPath that is getting a sequence rather than an single node, and represents something that needs to be customized.  The OOTB transform works on this XML:

```
<Order OrderID="10249">
	<CustomerID>22</CustomerID>
	<EmployeeID>6</EmployeeID>
	<OrderDate>1996-07-05T06:39:18</OrderDate>
	<RequiredDate>1996-08-16T03:39:38</RequiredDate>
	<ShippedDate>1996-07-10T14:39:39</ShippedDate>
	<ShipVia>1</ShipVia>
	<Freight>11.6100</Freight>
	<ShipName>Toms Spezialitäten</ShipName>
	<ShipAddress>Luisenstr. 48</ShipAddress>
	<ShipCity>Münster</ShipCity>
	<ShipRegion/>
	<ShipPostalCode>44087</ShipPostalCode>
	<ShipCountry>Germany</ShipCountry>
	<OrderDetails>
		<OrderDetail>
			<ProductID>14</ProductID>
			<UnitPrice>18</UnitPrice>
			<Quantity>9</Quantity>
			<Discount>0</Discount>
		</OrderDetail>
	</OrderDetails>
	<OrderDetails>
		<OrderDetail>
			<ProductID>51</ProductID>
			<UnitPrice>42</UnitPrice>
			<Quantity>40</Quantity>
			<Discount>0</Discount>
		</OrderDetail>
	</OrderDetails>
</Order>
```

I had to makd CustomerID and a few other things integers in order to run the extraction successfully, and then also to nest the OrderDetail instances within OrderDetails property blocks.

**Comment by grechaw** [comment]
Leaving the source document alone, I made this diff to the generated module to make the extraction work ... not too bad I think:

```
cgreer@cgreer:/tmp$ diff x.xqy y.xqy 
23c23
< (: Generated at timestamp: 2016-10-03T16:49:08.169908-07:00                         :)
---
> (: Generated at timestamp: 2016-10-03T16:52:31.438893-07:00                         :)
217,218c217,218
<  =>es:optional('OrderID',                xs:integer($source-node/@OrderID))
<  =>es:optional('CustomerID',             xs:string($source-node/CustomerID))
---
>  =>es:optional('OrderID',                xs:integer($source-node/OrderID))
>  =>es:optional('CustomerID',             xs:integer($source-node/CustomerID))
222c222
<  =>es:optional('OrderDetails',           es:extract-array($source-node/OrderDetails/*, northwind-Ref-Same-Document:extract-instance-OrderDetail#1))
---
>  =>es:optional('OrderDetails',           es:extract-array($source-node/OrderDetails, northwind-Ref-Same-Document:extract-instance-OrderDetail#1))
280c280
<  =>es:optional('UnitPrice',              xs:string($source-node/UnitPrice))
---
>  =>es:optional('UnitPrice',              xs:integer($source-node/UnitPrice))
```

**Comment by grechaw** [comment]
So back to you -- this is a place where the module needs a little massaging to work with the soruce data.  If the nesting is not as the codegen expects sometimes a /* will fix it.

**Comment by bsrikan** [comment]
Keys updated as the fix now returned values as expected. Changes available in PR # 175

**Comment by bsrikan** [comment]
Tests ran successfully in regression. Shipping the bug.
