### ISSUE TITLE
Bump up gradlew version

### ISSUE THREAD

**Issue by rjrudin** [marklogic/entity-services#150]
I'm following the instructions in http://ea.marklogic.com/features/data-integration/entity-services/, and I used gradlew, and I noticed it downloaded version 2.6.

I recommend going to at least version 2.14, which has some noticeable performance improvements in it that I believe were introduced in 2.13.

Version 3.0 is also out, and I recommend going with that over 2.14, but at least go with 2.14.

**Comment by grechaw** [comment]
in PR

**Comment by grechaw** [comment]
Pushed up to 3.1.
