### ISSUE TITLE
Cannot run "gradlew run"

### ISSUE THREAD

**Issue by rjrudin** [marklogic/entity-services#151]
I'm following the instructions at http://ea.marklogic.com/features/data-integration/entity-services/ , and for "gradlew run", Gradle errs out because it can't find the data-movement dependency:

$ ../gradlew run
:entity-services-examples:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':entity-services-examples:compile'.
> Could not find com.marklogic:data-movement:1.0-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/marklogic/data-movement/1.0-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/com/marklogic/data-movement/1.0-SNAPSHOT/data-movement-1.0-SNAPSHOT.pom
      https://repo1.maven.org/maven2/com/marklogic/data-movement/1.0-SNAPSHOT/data-movement-1.0-SNAPSHOT.jar
      file:/C:/Users/rrudin/.m2/repository/com/marklogic/data-movement/1.0-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/rrudin/.m2/repository/com/marklogic/data-movement/1.0-SNAPSHOT/data-movement-1.0-SNAPSHOT.pom
      file:/C:/Users/rrudin/.m2/repository/com/marklogic/data-movement/1.0-SNAPSHOT/data-movement-1.0-SNAPSHOT.jar
      https://jcenter.bintray.com/com/marklogic/data-movement/1.0-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/com/marklogic/data-movement/1.0-SNAPSHOT/data-movement-1.0-SNAPSHOT.pom
      https://jcenter.bintray.com/com/marklogic/data-movement/1.0-SNAPSHOT/data-movement-1.0-SNAPSHOT.jar
  Required by:
      entity-services-parent:entity-services-examples:unspecified

**Comment by grechaw** [comment]
It seems that the release went out with a snapshot dependency.

**Comment by grechaw** [comment]
Hi Kiran, we'll need to take another look at the release this week.  I'd like to just take care of these early version-related issues that @rjrudin has raised, and push things out again. 

https://github.com/marklogic/entity-services/issues/87

**Comment by grechaw** [comment]
Actually, I noted that the dependency is updated properly for the release tag, but I botched the master branch.  What branch are you using @rjrudin ?  We had considered leaving develop depending on SNAPSHOT DMSDK, but if that's inconvenient we could reconsider.

**Comment by rjrudin** [comment]
Ah, I'm on "develop", but that's apparently the default branch - i.e. following the instructions will clone the repo and you'll start on the develop branch. So at least per the instructions, a user will run into this issue, unless they change over to master.

**Comment by jmakeig** [comment]
EA users should be working off of `master`, no? A public release should be tagged on `master`. `develop` should be stable, but not necessarily aligned with a release tag.

**Comment by rjrudin** [comment]
Sounds right, but when you run "git clone https://github.com/marklogic/entity-services.git", you start off on the develop branch. Same is true for when you go to https://github.com/marklogic/entity-services - the default branch is develop.

**Comment by jmakeig** [comment]
Ah yes, we should change the default then. 

@grechaw do I have the workflow correct here? If so, can you please change the default branch?

**Comment by jmakeig** [comment]
> It seems that the release went out with a snapshot dependency.

@kkanthet, I thought all non-GA releases would have SNAPSHOT versions, for the sake of Maven. Is that not the case?

**Comment by kkanthet** [comment]
For EA release we mentioned will have EA versions and develop is the only place we will have SNAPSHOT.

I think what's missed here is during the release is 
- merge EA release to master branch 
- Change default branch to Master

**Comment by jmakeig** [comment]
> * merge EA release to master branch
> * Change default branch to Master

Yes, that sounds perfect.

**Comment by grechaw** [comment]
We merged last week.  Will make the change to default branch.

**Comment by grechaw** [comment]
OK I've changed the default branch to master now.  I'll close this issue as that's the remediation, but keep it coming!  You may after all want to try develop after the gradle version is updated :)
