### ISSUE TITLE
Only 3 databases created when running mlDeploy

### ISSUE THREAD

**Issue by rjrudin** [marklogic/entity-services#152]
The instructions at http://ea.marklogic.com/features/data-integration/entity-services/ state "You should see four new databases: entity-services-content, entity-services-modules, entity-services-schemas, and entity-services-triggers"

However, when I ran mldeploy, I only got 3 databases - the triggers database doesn't exist. 

I don't know if that's a problem or not, because I couldn't run the "run" step next. Assuming the triggers database is not needed, then the instructions just need a simple update.

**Comment by grechaw** [comment]
Yes, they do need an update -- I figured out how to suppress the triggers db creation later on in the game.

**Comment by grechaw** [comment]
Assigned to justin -- this is a sitelet issue.  I configured the project to suppress triggers db and didn't communicate that change.

**Comment by jmakeig** [comment]
Fixed in marklogic/marklogic-9-ea-sitelet@cea03756a7f36056f9d751b90f4319bd72b73360. I need to figure out how to update the live site still.
