### ISSUE TITLE
Documentation edit for changing ML properties

### ISSUE THREAD

**Issue by sastafford** [marklogic/entity-services#154]
Make sure to indicate in the setup that there is a second properties file that may need to be edited when you run _gradle run_ in the examples.  

src/main/resources/application.properties

I run a local virtual machine running on a separate address than localhost.  I had to make the changes to both gradle.properties and application.properties.

**Comment by grechaw** [comment]
Got it. Thanks

**Comment by grechaw** [comment]
Hi @sastafford were you referring to the EA-3 sitelet here or github?  github does mention this properties file  https://github.com/marklogic/entity-services/tree/master/entity-services-examples#step-two--run

**Comment by jmakeig** [comment]
@sastafford Please [file an issue on the EA sitelet](https://github.com/marklogic/marklogic-9-ea-sitelet/issues/new).

**Comment by jmakeig** [comment]
@sastafford Why did you have to change `src/main/resources/application.properties`? Those values are dependent on `gradle.properties`. Did you change the port number in the latter?

**Comment by jmakeig** [comment]
Fixed by marklogic/marklogic-9-ea-sitelet#40.
