### ISSUE TITLE
Backwards Compatibility with ML8?

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/entity-services#165]
Is there any value in making the codegen stuff backwards compatible with 8? Right now it uses the new XQuery 3.1 stuff (`=>` and `map:with`). That means it won't work on ML8.

But if it just used the current, uglier map interfaces then it would fly on 8.

**Comment by paxtonhare** [comment]
@jmakeig This has relevance for the data hub. Rather than having to release 2 versions of the hub I would much rather release 1 version that works in both 8 and 9+.

**Comment by grechaw** [comment]
@jmakeig , say the word and I'll prioritize this issue.  Of course I'd prefer if XQ 1.0-ml supported => in 8.  map:with is a trivial function to implement ourselves.

**Comment by paxtonhare** [comment]
@grechaw I guess you could use the

```xquery
xquery version "3.1";
```

in your prolog. Would still work with all instances of 8.x

**Comment by grechaw** [comment]
Yes, you're right @paxtonhare that would solve the issue.  There are some other things that have to be done in 3.1, but I don't think they would be too onerous.  It would be surprising to most MarkLogic developers, however, to be subject to the quirks of not having 1.0-ml (maybe)

The change is more about level of effort of changing the syntax I think.  I might have a => fetish, but I try to rationalize it as much as possible.  The other changes required for MarkLogic 8 compat:

* implement map:with somewhere that MarkLogic 8 codegen can get to it (would have to be within the generated module as originally designed, or in data hub code)
* implement es:extract-array and es:optional within the codegen module (or data hub code).

If we could ship an 'entity instance' library in 8.0-7 that could also bridge the gap.  So codegen modules could import the entity instance library for [the equivalents of] map:with, es:optional, es:extract-array

**Comment by grechaw** [comment]
I think we've backpedaled on this issue.  Most of our team thinks it important to move to and promote new language features, and in particular map:with and the arrow operator are considered important and incompatible changes in 9.  

This is a proposal to close this issue.

**Comment by paxtonhare** [comment]
Close it. we forked the hub so it's a non-issue now.

**Comment by grechaw** [comment]
Thanks @paxtonhare
