### ISSUE TITLE
Misplaced comments in instance-converter-generate()

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#170]
Can be removed:
`(: because this implementation uses an XML envelope.                                :)`

Misplaced reference:
`(: The following line identifies the type of this instance.  Do not change it.      :)`
Above comment should refer to:
=>map:with('$type', '<EntityTypeName>')

**Comment by grechaw** [comment]
I revamped the comments somewhat, I think addressing this issue in the process.

**Comment by bsrikan** [comment]
I have verified that the comments are generated OK now. Will ship the bug after tests/keys are updated and run OK in regression.

**Comment by bsrikan** [comment]
Tests running as expected. Shipping the bug.
