### ISSUE TITLE
Add xdmp:mapping false to version translator

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#172]
xdmp:mapping "false" has been added to the instance converter, but not yet to the version comparison module.

There appear to be side effects when I add it, so this issue is to track the change.

**Comment by grechaw** [comment]
In PR.

**Comment by grechaw** [comment]
Not much to do for QA here I think.  But you'll probably note the change going by.

**Comment by bsrikan** [comment]
Generated code now has xdmp:mapping false added. Changes not in PR yet. Will ship after creating a PR and successful regression run.

**Comment by bsrikan** [comment]
This is working as expected now and version-translator() code returns xdmp:mapping false. Shipping the bug.
