### ISSUE TITLE
deploying e2e and examples give MANAGE-INVALIDPAYLOAD error 

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#177]
Both e2e and examples give an error as below when "../gradlew mldploy" is run

`POST request for "http://localhost:8002/manage/v2/databases" resulted in 400 (Bad Request); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"400", "status":"Bad Request", "messageCode":"MANAGE-INVALIDPAYLOAD", "message":"MANAGE-INVALIDPAYLOAD: (err:FOER0000) Payload has errors in structure, content-type or values. Payload malformed: SEC-PRIV: xdmp:default-in-memory-geospatial-region-index-size() -- Need privilege: http://marklogic.com/xdmp/privileges/xdmp-default-in-memory-geospatial-region-index-size"}}`

@grechaw Can you please take a look.

**Comment by grechaw** [comment]
Yes, I saw this too and immediately went to the workaround of admin/admin.  It's clearly not our bug.

I'll alert Jake.

**Comment by grechaw** [comment]
Just saw Jake make a change related, bug 42519.

Could be that this will be fixed in the morning, maybe with a new database directory.

**Comment by jmakeig** [comment]
Friends don’t let friends run their tests as `admin`.

**Comment by grechaw** [comment]
... we won't speak of friends who BREAK THE BUILD ... :)

**Comment by bsrikan** [comment]
Bug 42519 has comments that the issue has been fixed and is in Test. Closing this task as e2e and examples have deployed OK in regression today.

**Comment by bsrikan** [comment]
Added label closed to this task so it closes 42538 in bugtrack
