### ISSUE TITLE
Spec needs update to include es:extract-array in version-translator

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#185]
version-translator sample code needs to be updated with es:extract-array in the functional spec

`=>es:with("prop4", json:to-array($source-instance/ET1/prop4 ! xs:int(.)))`

`=>es:with("referenceProperty", 
           ($source-instance/ET1/referenceProperty/ET1) !
           X:convert-instance(.))`

`(: Warning: potential data loss, truncated array :)
=>es:with("prop5", ($source-instance/ET1/prop5)[1])` to be replaced with 
`(: Warning: potential data loss, truncated array :)
=>es:optional('prop5', casting-function( fn:head($source-node/ET1/prop5) ) )`

**Comment by grechaw** [comment]
Just updated svn with changes to spec

**Comment by bsrikan** [comment]
Verified specs and looks good. Shipping the bug.
