### ISSUE TITLE
Order of functions returned per ET type for version translator keeps changing

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#186]
Lets say source and target models have 2 ET types for ex Customer and Product. version translator generates code such that the order of functions returned keeps changing.

ie on first run its
X-convert-instance-Customer() { ... }
X-convert-instance-Product() { ... }

on second run its 
X-convert-instance-Product() { ... }
X-convert-instance-Customer() { ... }

Needs to be consistent.

**Comment by grechaw** [comment]
verified.  should be a simple use of json:object rather than map:map.

**Comment by grechaw** [comment]
OK I've a fix ready for this and will add to PR #187

**Comment by bsrikan** [comment]
This is working as expected now. Functions are returned in the same order at all times.
Shipping the bug.
