### ISSUE TITLE
attachments are output twice when calling mymodule:instance-to-envelope()

### ISSUE THREAD

**Issue by koenh1** [marklogic/entity-services#190]
should line
https://github.com/marklogic/entity-services/blob/develop/entity-services/src/main/xdmp/entity-services/entity-services-codegen.xqy#L278
not exclude $attachments also ?
As it stands now, calling instance-to-envelope() will output the attachments twice.

**Comment by grechaw** [comment]
Your reasoning makes sense to me, but I've not noticed the behavior.   I would have thought that no names staring with '$' would be castable as NCName, in which case excliding $type is unreachable code.  Thanks for finding the issue @koenh1

**Comment by grechaw** [comment]
"$type" castable as xs:NCName 

This evaluates to 'false'  .  So the bug here is rather that the second part is unreachable code.  $attachments should also not be emitted.

**Comment by grechaw** [comment]
I think this is just shippable, @bsrikan

**Comment by bsrikan** [comment]
Sure, will wait for regression results tomorrow and ship.

**Comment by bsrikan** [comment]
Tests running fine in regression. Shipping the bug.
