### ISSUE TITLE
es:model-get-test-instances array of refs behavior is surprising

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/entity-services#192]
This is probably more a request for clarification than a bug report.

The spec currently says the following about `model-get-test-instances`:

> If a property is of type 'array', then a sequence of three elements is emitted, to emphasize that there are multiple values for that property

I have a property that is an array of entity refs, and I see two surprising things about the resulting test instance:

- The test instance only generates one item in the array, not 3, as spec'd. IDC, but it would be good to know how it is supposed to behave so the apidoc can be corrected if necessary.
- There are some recursive entity refs (A has a B has a A) , and the danger is handled by devolving the nested property to a string value eventually. That's probably WAI as it has to have some stop strategy, but I thought I should mention it.

The model descriptor looks like the following. Notice that a Person contains a `friend` property that is an array of Person refs. (I know, not a realistic way to do that. I was reaching.)
```json
{ "info": { 
    "title": "Example", 
    "description": "ES Examples",
    "version": "1.0.0",
  },
  "definitions": {
    "Name" : {
      "properties": {
        "first": { "datatype": "string" },
        "middle": { "datatype": "string" },
        "last": { "datatype": "string" }
      },
      "required": ["first", "last"]
    },
    "Person": {
      "properties": {
        "id": { "datatype": "int" },
        "name": { 
          "$ref": "#/definitions/Name", 
        },
        "bio": { "datatype": "string" },
        "rating": { "datatype": "float" },
        "friend": {
          "datatype" : "array",
          "items": { "$ref" : "#/definitions/Person" }
        }
      },
      "required": ["id", "name"],
      "rangeIndex": ["rating"],
      "wordLexicon": ["bio"]
    }
}}
```
The generated test Person instance looks like the following. Note that this poor Person only has one friend and that Person/friend/name/Name and /Person/friend/Person/friend/Person are both just strings.
```xml
<Person>
  <id>123</id>
  <name>
    <Name>
      <first>some string</first>
      <middle>some string</middle>
      <last>some string</last>
    </Name>
  </name>
  <bio>some string</bio>
  <rating>123</rating>
  <friend datatype="array">
    <Person>
      <id>123</id>
      <name>
        <Name>some string</Name>
      </name>
      <bio>some string</bio>
      <rating>123</rating>
      <friend datatype="array">
        <Person>some string</Person>
      </friend>
    </Person>
  </friend>
</Person>
```

**Comment by grechaw** [comment]
Hi Kim, good catches.  The first was a deliberate change -- I remember editing the spec but I sure don't see those edits now!  

The second issue -- it's not actually devolving to a string, although I admit it looks like that -- those are 'references' rather than embedded objects.  So there is a devolution, but that is indeed the valid way to represent a reference to another instance.

**Comment by kcoleman-marklogic** [comment]
Definitely not a bug, then. Thanks for the clarifications, Charles.
