### ISSUE TITLE
Person example failing with NPE

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/entity-services#201]
Could just be some mismatch between the current state of DMSDK and the current state of ES as I just pulled new Java Client sources this morning. Or maybe I need a newer server? Mine is from 10/24. Will try a server upgrade first. 

`./gradlew --stacktrace --info runExamplePerson`

```
...
Verifying person instances with SPARQL.
This query joins instance data to the model and returns all IRIs that are typed 'Person'
prefix es: <http://marklogic.com/entity-services#> prefix : <http://example.org/example-person/> select ?person ?typeName  where
 { ?person a ?personType .  ?personType es:title ?typeName }
"person"        "typeName"
pt:122 Person
pt:123 Person
pt:124 Person
pt:David%20Byrne       Person
pt:Justin_Makeig       Person
pt:Kim_Coleman Person

Exception in thread "main" java.lang.NullPointerException
        at com.marklogic.entityservices.examples.person.PersonExplorer.table(PersonExplorer.java:82)
        at com.marklogic.entityservices.examples.person.PersonExplorer.runOpticQuery(PersonExplorer.java:195)
        at com.marklogic.entityservices.examples.person.PersonExplorer.main(PersonExplorer.java:226)
> Building 75% > :entity-services-examples:runExamplePerson
```

**Comment by kcoleman-marklogic** [comment]
Alas, a server upgrade did not help. The example assumes a lot of knowledge I don't have (optic, sparql, etc.), so I'm not sure what threads to pull on. Suggestions?

**Comment by grechaw** [comment]
No, this is an optic query that returns no results, and my example code throws NPE for this.  Not the final state of examples, so I'll put this in "fix" status.

**Comment by grechaw** [comment]
Put in some code to handle the NPE situation.

**Comment by kcoleman-marklogic** [comment]
Presently blocked on testing this by my inability to deploy the example successfully. See #198 .

**Comment by kcoleman-marklogic** [comment]
I was able to successfully deploy and run the example. No NPE or other errors. Shipping.
