### ISSUE TITLE
instance-get-attachments won't return JSON data

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/entity-services#207]
I have a mixed set of XML and JSON source data from which I created envelope documents. I find that `es:instance-get-attachments` works fine for the envelope docs derived from XML, but it returns nothing for envelope docs derived from JSON.

For example, given the following envelope doc, you get nothing back from `es:instance-get-attachments`:
```
<es:envelope xmlns:es="http://marklogic.com/entity-services">
  <es:instance>
    <es:info>
      <es:title>Person</es:title>
      <es:version>0.0.1</es:version>
    </es:info>
    <Person>
      <id>2345</id>
      <firstName>Martha</firstName>
      <lastName>Washington</lastName>
      <fullName>Martha Washington</fullName>
    </Person>
  </es:instance>
  <es:attachments>{"pid":2345, "first":"Martha", "last":"Washington"}</es:attachments>
</es:envelope>
``` 
I should be able to get my JSON back out as a string so I can rehydrate it with xdmp:from-json-string. For example, I originally overlooked this function, so I inadvertently did an end run around it like what's below, and it worked fine:
```
let $matches := (: an envelope doc search happens here :)

(: extract the original source, as a node :)
for $attachment in $matches/es:envelope/es:attachments/node()
return typeswitch ($attachment)
  case element() return $attachment
  case text() return xdmp:from-json-string($attachment)
  default return ()
```
Imagine my chagrin when I found I couldn't replace that filthy little xpath expression with `es:instance-get-attachments`. Oh, the Humanity!

**Comment by kcoleman-marklogic** [comment]
QC workspace to facilitate playing with this. You prolly don't need it - the model is just your Person example - but I'm all for lowering barriers. Silly github wouldn't let me attach the workspace as an XML file, so I zipped it up to fake it out. Stupid software tricks.

[json-attachment-bug.zip](https://github.com/marklogic/entity-services/files/573347/json-attachment-bug.zip)

**Comment by grechaw** [comment]
I've got a fix for this that we can triage as appropriate.

**Comment by bsrikan** [comment]
I have added new test to verify this bug. Works in my local. Will wait for regression run tomorrow and ship.

**Comment by bsrikan** [comment]
Test works OK in regression. Shipping the bug.
