### ISSUE TITLE
search options comment about dup items in confusing wrt primary key

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/entity-services#212]
I have a primary key named "id" in my model. In addition, I tagged this property for a range index. 

Options generation produces 2 constraints on id, one a values constraint (from the primary key), and the other a commented out path range constraint (from the rangeIndex):
```
  <search:constraint name="id">
    <search:value>
      <search:element ns="" name="id"/>
    </search:value>
  </search:constraint>
  <!--This item is a duplicate and is commented out so as to create a valid artifact.
 <search:constraint name="id" xmlns:search="http://marklogic.com/appservices/search">
  <search:range type="xs:int" facet="true">
    <search:path-index xmlns:es="http://marklogic.com/entity-services">//es:instance/Person/id</search:path-index>
  </search:range>
</search:constraint>
-->
```
I get that the options generation can't include both of them since the names would be the same, but I find the "This item is a duplicate…." comment confusing. It's not a duplicate in my model. It's not even a duplicate in the search options - they're two different constraint types. 

It might be better to say "The name of this constraint is a duplicate...".

**Comment by grechaw** [comment]
excellent point.

**Comment by grechaw** [comment]
What do you think of:

options: "The name of this constraint is a duplicate in the generated XML. It is within a comment so that the XML may be valid, but you may need to edit for your use case."

schemas: "XSD schemas cannot have conflicting configuration for the same element name. This model has two elements of the same name, so the following is commented out."

**Comment by grechaw** [comment]
I've included a fix for this issue in the outstanding PR

**Comment by bsrikan** [comment]
Regression running ok after key updates. Passing over to you @kcoleman-marklogic for review.

**Comment by kcoleman-marklogic** [comment]
Looks fine to me.
