### ISSUE TITLE
func spec: cleanup TDE discussion

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/entity-services#215]
The section of the spec that describes the characteristics of the TDE template is kind of confusing right now. In your copious spare time, please review and revise. I don't require this for EA4, but I need it, say, some time between now and Jan.

I am referring to the section with the following contents. I have inserted my questions/comments in italics.

* The schema for all templates is has the title of the entity type document. The root context for the template is //es:instance. _What does "the schema for all templates..." mean? I see nothing in the template corresponding to this._
* For each entity type, create a triple template that emits two triples:
* Context is `./{entityTypeTitle}` _FYI use of "title" here is confusing. It's just the name._
* create a subject identifier for this triple, based on concatenating the entity type with the value of this type's primary key, if there is one. If there is no primary key specified for a given type, then no triples will be emitted, as there's no guarantee of a durable unique identifier.
* Make one triple such that `<subjectIRI> a <entityTypeIRI>`. This triple establishes that this instance is of the type defineby by entity type.
* Make one triple such that `<subjectIRI> rdfs:isDefinedBy <documentURI>`. This triple establishes how to join instance/class membership to the instance document.

For each entity type, create a row template such that:
* Context is `./{entityTypeTitle}`
* There is one column for each non-array type. If a property is an array type, it will be supported with a related view, so will not be present in the main one.
* If the dataype is 'iri' it is indexed as IRI...[snip]. _Does saying it is "indexed as IRI" imply something different from the way you talk about the datatype everywhere else?_
* If the property is a local $ref then the datatype is established by finding the primary key of the referent, and using its datatype.
* If the property is an external reference it will simply be included as a string column, and must be customized to make sense.
* For each array column create a view with the name `./{EntityTypeTitle}_columnName`
* For scalar arrays, this view has two columns. One locates the primary key value of the instance. The other is the value of each array. That value will either be the value from the array, or the value of a referent's primary key. _What does it mean to say one column "locates" the primary key value? What is "the value of each array"? Does that mean all the values concatenated together? One row per item? When is it the value vs a primary key? (We already said it is a scalar array.)_
* If the reference is local, then there are two possibilities. _Is this still in the context of an array?_
  * If the referent has no primary key, then the values from the referent should be in the  `./{EntityTypeTitle}_columnName` view (rather than just two columns). In such situations, the view from which these columns were "taken" is not emitted. So there is one column to refer to the containing type's primary key (string as a default if its missing), and one column for each of the joined row's columns. _I understand NOTHING in this paragraph. Can you put it in user-speak for me to copy pasta?_
  * If the reference has a primary key, then the '_columnName' view has just two columns (like a scalar array). In this case, the second column's name and type are equal to the referent (the primary key of the referent's view).
* If a property is not required, then it will be marked as nullable. If there are no required properties in the entity-type, then the generated extraction template will not be emitted, as it's not valid. An XML comment will indicate where the row definition is left out. For the purposes of extraction templates, the primary key is considered a required property. _If there are no required props, is the whole template omitted, or just one row def? You say both here._

**Comment by kcoleman-marklogic** [comment]
More from the same section. At the bottom where it talks about customization, you say:

* If there is no primary key for an entity type with an array, then it's up to the user to join the array values to the rest of the entity.

Earlier, you say no template is generated for an entity type that has no primary key, so I don't understand what this is saying. This is apparently saying something different, but I don't understand what.

**Comment by grechaw** [comment]
Ach, what a mess! Given what you've said about priority I'll defer editing this  now, but recognize a distinct need to go back over this section and make it sensible.

**Comment by grechaw** [comment]
In progress this week.

**Comment by grechaw** [comment]
OK I've checked in some (I hope) better language for TDE.  Putting in your court for now but send back with more questions and requests for clarification.

**Comment by kcoleman-marklogic** [comment]
Thanks, Charles. I am, of course, never satisfied, so I still have some linger questions.

The following is unchanged, and  I still don't understand what it means in the context of the template. What are the user implications?
* The schema for all templates is has the title of the entity type document.

The following is still present, and I still do not understand its significance to the user:
* If the property's dataype is 'iri' its TDE scalar type is as IRI.

I do not find this following to be true. Rather, a comment is generated saying no template can be generated for that type. Let me know if that is not WAI.
* If an entity type has no required properties, then the emitted template for that type will be within an XML comment.

**Comment by kcoleman-marklogic** [comment]
Still have a few lingering questions about this section of the spec, which I sent to Charles via email yesterday. (Forgot about this bug!)

**Comment by grechaw** [comment]
Your email comments were very pertintent.  I also was confused when I read the spec on these parts.
