### ISSUE TITLE
ES guide : there is no api named query-options-generate

### ISSUE THREAD

**Issue by rashiatmarklogic** [marklogic/entity-services#217]
I think you wanted to say search-options-generate() in the following line: 
You can use es:query-options-generate to create a set of query options suitable for use with the Search API and the Client APIs.

**Comment by kcoleman-marklogic** [comment]
You're correct. This has been fixed. If you want to check it, you're welcome to do so. Otherwise, I will just tag this as ship.

**Comment by rashiatmarklogic** [comment]
Great ! Will check tomorrow.

**Comment by rashiatmarklogic** [comment]
Looks good now.
