### ISSUE TITLE
ES: guide - wrong languages 

### ISSUE THREAD

**Issue by rashiatmarklogic** [marklogic/entity-services#218]
Getting Started Using XQuery
This section uses Server-Side JavaScript and JSON to introduce the Entity Services APIs. If you prefer to use XQuery and XML, see Getting Started Using JavaScript.

Should be :::

Getting Started Using XQuery
This section uses Xquery and XML to introduce the Entity Services APIs. If you prefer to use Server Side Javascript and JSON, see Getting Started Using JavaScript.

**Comment by kcoleman-marklogic** [comment]
This is fixed.

**Comment by rashiatmarklogic** [comment]
Good to go.
