### ISSUE TITLE
Arrays and items

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/entity-services#219]
Is the datatype = 'array' and items: {} format a product of the Open API format?

I ask because it's a little bit funky. By that I mean that you might end up having to code some logic in your client code to deal with arrays. For example when to set a value in datatype vs items.datatype. 

I'm doing this for the hub UI and it gets pretty complicated.

**Comment by grechaw** [comment]
I agree, it is funky.   I also found it complex to cope with it.  And yes, it's part of the whole JSON Schema thing.  On the other hand, there must be code out there that deals with this exact structure, since it is indeed part of JSON Schema...

**Comment by grechaw** [comment]
anything more to do with this issue @paxtonhare ?
