### ISSUE TITLE
Update comments in version-translator

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#220]
@grechaw I am creating this issue really for the third point below, but thought it would be OK to add other 2 issues that we discussed over chat as well.

Comments in version-translator needs more clarity as to what is the input to convert-instance-X() functions. 

Following three places needs update:
1. Comment before convert-instance-X() function:
This function expects either a canonical document or an envelope document as input

2. Function where copy-attachments() is called
A preceding comment to mention that attachments will be visible in output if available in the the input. For example -- a canonical input wont have attachments but an envelope would

3. Commented out function for the case where Entity type X is in source document but not in target document:
The generated function here is missing copy-attachments() function call. So a function call and comment as indicated in point 2 is required.

**Comment by bsrikan** [comment]
Test for point3:

```
import module namespace es = "http://marklogic.com/entity-services" at "/MarkLogic/entity-services/entity-services.xqy";
es:version-translator-generate(fn:doc( 'srcHasETTgtDsnt-Src.json'), fn:doc('srcHasETTgtDsnt-Tgt.json'))
```

Entity Type: Product

**Comment by grechaw** [comment]
I've made these changes and will put into a PR now.  I'm not completely sure whether my choices for wording will satisfy you, but we shall see.

**Comment by bsrikan** [comment]
I have added key updates to verify this bug. Updated sandbox test as well. Works in my local. Will wait for regression run tomorrow and ship.

**Comment by bsrikan** [comment]
Tests run OK in regression. Shipping the bug.
