### ISSUE TITLE
Include a default grammar when I generate the search options

### ISSUE THREAD

**Issue by sastafford** [marklogic/entity-services#223]
As a developer
I want to TITLE
So that I can have a base grammar that I can modify later.  

Right now, there is no default grammar when I generate search options.  By including a default grammar I could quickly show users/customers range queries from a query string.  

Example: 
q= salary GT 10000

```xml
<grammar>
    <quotation>"</quotation>
    <implicit>
      <cts:and-query strength="20" xmlns:cts="http://marklogic.com/cts" />
    </implicit>
    <starter strength="30" apply="grouping" delimiter=")">(</starter>
    <starter strength="40" apply="prefix" element="cts:not-query">-</starter>
    <joiner strength="10" apply="infix" element="cts:or-query" tokenize="word">OR</joiner>
    <joiner strength="20" apply="infix" element="cts:and-query" tokenize="word">AND</joiner>
    <joiner strength="30" apply="infix" element="cts:near-query" tokenize="word">NEAR</joiner>
    <joiner strength="30" apply="near2" consume="2" element="cts:near-query">NEAR/</joiner>
    <joiner strength="50" apply="constraint">:</joiner>
    <joiner strength="50" apply="constraint" compare="LT" tokenize="word">LT</joiner>
    <joiner strength="50" apply="constraint" compare="LE" tokenize="word">LE</joiner>
    <joiner strength="50" apply="constraint" compare="GT" tokenize="word">GT</joiner>
    <joiner strength="50" apply="constraint" compare="GE" tokenize="word">GE</joiner>
    <joiner strength="50" apply="constraint" compare="NE" tokenize="word">NE</joiner>
  </grammar>
```

**Comment by sastafford** [comment]
Email discussion on 11/28

-----Original Message-----
From: Justin Makeig 
Sent: Monday, November 28, 2016 2:46 PM
To: Charles Greer <Charles.Greer@marklogic.com>
Cc: Scott Stafford <Scott.Stafford@marklogic.com>
Subject: Re: RFE?

Yes, please create a GitHub issue with the discussion below.

Justin

**Comment by ehennum** [comment]
We have always discouraged developers from defining their own grammar.

If anything, we're moving farther in that direction.  With the availability of SJS tools like JISON, that gives developers a better path for defining performant grammars.

We should think long and hard about whether entity services should encourage people to modify search grammars.

**Comment by sastafford** [comment]
@ehennum - I agree with the need to decouple grammar from search options.  But the fact that entity services generates search options encourages use of custom grammars via the search options.  In fact, this is the first I've heard of not using a custom grammar not offered by the Search API. 

If you could recommend some other options for search grammar transforms I'd be happy to look into.

In the short term this should be fixed.

**Comment by grechaw** [comment]
Thoughts, @jmakeig ?

Adding boilerplate to the generated search options is trivial.  I also had no idea that customizing the grammar was in general use.    

@sastafford , we'll be interested to know whether cts:parse, were it to be available, would meet your needs.  It's a faster parsing method, at the expense of some of the configurability of the Search API grammar.

**Comment by ehennum** [comment]
@sastafford - yes, custom grammars are a documented capability, but we expect most Search API users won't create custom grammars.  Throwing the complexity of the grammar in the middle of the search options is a good way to send people running for the exit. 

On the alternatives, I've done experiments with JISON in SJS.  From what I saw, JISON had more flexibility and better performance than a dynamic, per-request TDOP custom grammar.

Last I heard, Joe Bryan has had good experiences with PEG.js in SJS.

**Comment by jmakeig** [comment]
> `salary GT 10000`

@sastafford, I don’t understand the motivating example. If `salary` is configured as a range constraint don’t you get that behavior by default?

**Comment by kcoleman-marklogic** [comment]
I think it would be terrible to include the grammar. Even setting aside the elephant-sized fact that we wish to discourage the use of custom grammars, including the grammar in the generated options adds a lot of noise that will not be needed/used by most users.

Just as you're able and expected to customize the code generated by ES, you can and should customize the options. If you want to use a custom grammar, nothing stops you from using `search:get-default-options()` to get the base grammar, making whatever changes you like to it, and then adding it to the options generated by ES.

**Comment by sastafford** [comment]
@jmakeig - thank for bringing to my attention that I am an idiot and not using the correct options file.  The grammar GT, LT, GE, LE is implicitly declared in the search options.  I have verified in my test environment.  I'm sorry for spinning up everyone about this.
