### ISSUE TITLE
Consider refactoring of instance-converter functions to have separate let and return blocks

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#232]
In the data hub impementation, @paxtonhare used a style for the extraction functions that seems to me an improvement over how Entity Services does it.

```xquery
define function ns:extract-instance-Type() {
  let $v1 := /spath/expression1
  let $v2 := /spath/expression3
  let $v3 := /spath/expression4

  return
  json:object()=>map:with('v1', $v1)=>...
```

This style has the benefit of putting all customization at the top of the function, and also makes it more obvious that the actual structure of the instance is more hands-off.

If docs can contain the changes to examples for 9.0-1 (I can help) I think that the change to this style will help users of the feature a lot.

**Comment by kcoleman-marklogic** [comment]
It's fine.

I do have one comment, though: I was always under the impression that evaluating code in variables (rather than inline) is kind of anti-pattern for XQuery because it defeats the optimizer. If this is so, is this a smart choice? 

(Mind you, I tend to code like this anyway because I still haven't shaken off my procedural upbringing and stubborn preference for maintainability over optimal performance.)

**Comment by grechaw** [comment]
I think that the maintainability is the motive here.  But your concern is legit.  I suppose we need to weigh the importance and validity of this anti-pattern idea and move ahead based on consultation with pattern gurus.

**Comment by jmakeig** [comment]
Let's not make this change in 9.0-1 until we weigh the performance/usability impacts. I don’t find the Data Hub style that much more readable.

**Comment by grechaw** [comment]
I'm going to reopen this issue for 9.0-2.  In looking at aligning data hub, and especially in making JavaScript modules, the codegen can be simplified by adopting this style for both XQ and Javascript.

I am convinced that the readability is much better with this style -- the variables one has to populate are explicitly named.  It is possible that inlining the expressions will speed up processing in XQ, but probably not much.  For argument, the JS will look something like

```
var firstName = fn.head( source.xpath("/source/first_name");
var lastName = fn.head( source.xpath("/source/last_name");

return { "firstName" : firstName, "lastName" : lastName }
```

it's easy to see the relationship between key names and variables, and the XQ will look very similar to this:

@paxtonhare what do you think?

**Comment by ehennum** [comment]
One minor syntax quibble -- var is now an antipattern in JavaScript and deprecated in favor of const to define constants or let to define mutables.

On the particular issue, the following would be idiomatic in JavaScript (depending on where one lands on the religious war about the trailing semicolon):

    return {
        firstName: fn.head(source.xpath('/source/first_name'),
        lastName: fn.head(source.xpath('/source/last_name')
        };

**Comment by grechaw** [comment]
Finally I understand where var went and why, thank you @ehennum .

Paxton had raised this question originally specifically to separate the ideas of constructing individual properties from constructing the final JavaScript objects,  because sometimes populating the individual properties is a simple expression like these, and sometimes it may require more code.

Does your inclusion of the JS block indicate that inlining would be preferable to using a let?

**Comment by jmakeig** [comment]
Yes, always `const` and sometimes `let`, going forward. 

How difficult would it be to generate code that ran in MarkLogic 8 as well? There are no runtime dependencies that would require 9 on the *generated* code are there? Would it be significantly more difficult to parameterize the `var`/`const` option? I’ve heard generating on 9 and running on 8 as a request to more gradually transition to 9.

**Comment by grechaw** [comment]
> Would it be significantly more difficult to parameterize the var/const option?

no it wouldn't.  I'm going to have to create js and XQ versions of the module's syntax.   Making another option for this keyword difference wouldn't add too much complexity.

**Comment by ehennum** [comment]
Regarding whether inlining is preferred, many or maybe even most JavaScript developers embrace functional programming to at least some extent.  Witness Array.prototype.map()

That said, I agree that legibility is a huge concern when generating editable code.  So, if constant assignments are more legible instead of more verbose....

**Comment by grechaw** [comment]
> Would it be significantly more difficult to parameterize the var/const option?

That said, it's also a near-trivial customization for those back-porting.

**Comment by grechaw** [comment]
In reviewing codegen with Matt Turner yesterday, I think that the extensive use of comments in the XQ modules is wrong-headed.  I end up just deleting it all anyway when I use entity services, and it may get in the way of having clearly readable code, rather than comments.  There's a balance to be struck, of course, but I'd like to float replacing the very long comment blocks with, say, a link to documentation.

**Comment by kcoleman-marklogic** [comment]
Yeah, I agree. I found the code difficult to read when I was working on it, and generally removed the comments from any snippets I discussed in detail so that the focus was just on the code.

I cannot contain switching this up for 9.0-2, but I could do something for 9.0-3. (Unless you want handle it through github wiki stuff, of course.)

**Comment by rashiatmarklogic** [comment]
I second that.

**Comment by grechaw** [comment]
Here is a draft proposal for a 'new style' instance module function:

```
(:~
 : Extracts instance data, as a map:map, from some source document.
 : @param $source-node  A document or node that contains
 :   data for populating a Customer
 : @return A map:map instance with extracted data and
 :   metadata about the instance.
 :)
declare function eCommerce:extract-instance-Customer(
    $source as node()?
) as map:map
{
    let $source-node := es:init-source($source, 'Customer')
    (: begin customizations here :)
    let $id  :=           $source-node/id ! xs:int#1
    let $firstName  :=    $source-node/firstName ! xs:string#1
    let $lastName  :=     $source-node/lastName ! xs:string#1
    let $email  :=        $source-node/email ! xs:string#1
    let $ssn  :=          $source-node/ssn ! xs:string#1
    let $phone  :=        $source-node/phone ! xs:string#1
    (: The following property is a local reference.  :)
    let $billTo  :=       $source-node/billTo ! eCommerce:extract-instance-Address#1
    (: The following property is a local reference.  :)
    let $shipTo  :=       $source-node/shipTo ! eCommerce:extract-instance-Address#1
    let $segment  :=      $source-node/segment ! xs:string#1
    let $region  :=       $source-node/region ! xs:string#1
    (: end customizations :)

    let $instance := es:init-instance('Customer')

    return
    if (empty($source-node/*)) 
    then $instance
    else $instance
        =>   map:with('id', $id)
        =>es:optional('firstName', $firstName)
        =>es:optional('lastName', $lastName)
        =>es:optional('email', $email)
        =>es:optional('ssn', $ssn)
        =>es:optional('phone', $phone)
        =>es:optional('billTo', $billTo)
        =>es:optional('shipTo', $shipTo)
        =>es:optional('segment', $segment)
        =>es:optional('region', $region)
    (: Comment or remove the following line to suppress attachments :)
        =>es:add-attachments($source-node, $source)
};
```

**Comment by bsrikan** [comment]
Test updates in PR #310. Will ship after successful regression run

**Comment by bsrikan** [comment]
Shipping the issue.
