### ISSUE TITLE
Better paths in Query Console examples

### ISSUE THREAD

**Issue by jmakeig** [marklogic/entity-services#238]
```xquery
declare variable $PATH as xs:string := "file:///C:/share/git/entity-services";
```

The [current implementation](https://github.com/marklogic/entity-services/blob/develop/entity-services-examples/example-races/races-qc.xml#L6) breaks if paths have spaces (mine do). 

```xquery
declare variable $PATH as xs:string := "file://" || xdmp:url-encode("/xx/yy/zz/entity-services", true());
```

**Comment by grechaw** [comment]
So something like:

```
declare variable $PATH as xs:string := "/xx/yyy/xxx/entity-services";
declare variable $PATH_URI := "file://" || xdmp:url-encode($PATH)
```

?

**Comment by jmakeig** [comment]
Take look at #239.

The places where you use `$PATH` in an `fn:doc()` call need to be URL encoded.

**Comment by grechaw** [comment]
I'm going to give it a try to fix the document uris so as to not need file paths.

**Comment by grechaw** [comment]
heads up to @bsrikan that we may need another ea-4 change

**Comment by bsrikan** [comment]
This bug was tested for examples and e2e. $PATH is no longer being used and the same has been applied to all data loads from different sources. Shipping the bug.
