### ISSUE TITLE
running ./gradlew genCode gives "no user provided" error

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#242]
Run ./gradlew genCode from command line to get the error.

**Comment by grechaw** [comment]
Fixed this issue with commit to develop branch 1a1ed875bc937c33ed6554f49d6315d705bd6914

**Comment by grechaw** [comment]
assigned to @bsrikan to cover changes in e2e directory.

**Comment by bsrikan** [comment]
Updated application.properties in e2e as well to include mlAdminUsername and mlAdminPassword to resolve the error. Works ok now. Shipping the bug.
