### ISSUE TITLE
search-options-generate() shouldnt make tuples if less than 2 indexes are defined

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#243]
Currently search-options-generate() makes a tuple with 1 range. 

Ex: northwind.xml in e2e

  <search:tuples name="Product">
    <search:range type="xs:decimal" facet="true">
      <search:path-index xmlns:es="http://marklogic.com/entity-services">//es:instance/Product/ProductID</search:path-index>
    </search:range>
  </search:tuples>

**Comment by grechaw** [comment]
Looking into this now, I expect a quick fix.

**Comment by bsrikan** [comment]
Added test and is available in latest QA PR #251

**Comment by bsrikan** [comment]
Test running ok in regression. Shipping the bug.
