### ISSUE TITLE
Move extractions for all sources into a single module?

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#245]
In conversation with @bsrikan it seems that the races example could be improved, with regard to suggested best practice.

I created the example with two conversion modules for the first version of Races.  The first extracts one source, and the second extracts another.  

It might be better to put both extractions into a single module, to emphasize that all of those extractions are feeding instance data of the same schema.  

This issue is to consider this idea, then implement if we decide to move forward.  It would be a matter of only 30 minutes to change the modules around.

**Comment by grechaw** [comment]
On track for merging with version example, which is still in progress.

**Comment by grechaw** [comment]
In PR

**Comment by bsrikan** [comment]
Verified the merge and tested races-qc.xml. Updated races-qc.xml after testing and the same is available in PR #260 	314ef12
Looks good.

**Comment by bsrikan** [comment]
This is working as expected now. All tests in races-qc.xml work ok post this bug fix. Shipping!
