### ISSUE TITLE
TDE fails with BADVALEXPRESSION when primaryKey has a datatype other than string

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#247]
Error is in the <val> element of subject-iri in the tdex file and has to be casted to string now explicitly in order to make it work if the primary Key is not a string datatype:

<var>
	  <name>subject-iri</name>
	  <val>sem:iri(concat("http://marklogic.com/test/Northwind-0.0.1/Order/", fn:encode-for-uri(xs:string(./OrderID))))</val>
	</var>

Stack Trace:
Local message: failed to apply resource at internal/apply-transform: Internal Server Error. Server Message: TDE-INDEX: Error applying template Northwind-0.0.1.tdex to document /upconverts/orders/10261.xml: TDE-EVALFAILED: Eval for $subject-iri='sem:iri(concat("http://marklogic.com/test/Northwind-0.0.1/Order/", fn:encode-for-uri(./OrderID)))' returns TDE-BADVALEXPRESSION: Invalid val expression: XDMP-ARGTYPE: (err:XPTY0004) arg1 is not of type xs:string? . See the MarkLogic server error log for further detail.

**Comment by grechaw** [comment]
I've got a fix in place for this now.

**Comment by bsrikan** [comment]
Other area where I think this bug might have an impact is the table view. As suggested by Fayez and per TDE spec (http://pubs.marklogic.com/engweb/specifications/functional/b9_0/Template_Driven_Data_Extraction.html#template-structure), I added <view-layout>sparse</view-layout> in version 2 of the tdex and expected all the columns from both templates to show up. It did so for Customer table and did not for Order and Product. Customer has primary key CustomerID which is string, whereas datatype for other two is integer.

**Comment by bsrikan** [comment]
Added test and is available in latest QA PR #251.

**Comment by bsrikan** [comment]
Test running ok in regression. Shipping the bug.
