### ISSUE TITLE
Schema gen gives invalid coercion when input has 0 instance

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#250]
While testing the bug fix for #240 in PR #248 found this issue where schema gen throws invalid coercion error for input with no instance.

Doc:
<es:envelope xmlns:es="http://marklogic.com/entity-services">
</es:envelope>

Test:
import module namespace es = "http://marklogic.com/entity-services" at "/MarkLogic/entity-services/entity-services.xqy"; 
es:schema-generate(doc('test-envelope-no-instances.xml'))

**Comment by bsrikan** [comment]
Discussed with @grechaw. Will be good to have a fix in #248 itself since schema-gen, extraction-template and get-test-instances functional tests error out with following exception:


java.lang.RuntimeException: com.marklogic.entityservices.TestEvalException: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at eval: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $model as element(es:model) -- Invalid coercion: fn:doc("test-envelope-no-instances.xml")/es:envelope as element(es:model)for test-envelope-no-instances.xml

**Comment by grechaw** [comment]
Um, but this document is a test envelope, not a model.  Why are you trying to run schema-generate on it?

**Comment by bsrikan** [comment]
Maybe because I had inserted the envelope in the database. So far all the documents in the database have been descriptors. schema-generate and other functional tests validate every descriptor doc stored in the content database.

Maybe I should delete the document after the test is run.

**Comment by kcoleman-marklogic** [comment]
Or change the tests to differentiate between artifacts and instances using directories or collections. That's what I do in the documentation examples. Models go in /models/, all my Person envelope documents are in a "person-envelope" collection, etc.

**Comment by bsrikan** [comment]
Thanks Kim. Thats exactly how I have handled it. Have a separate dir for such documents that dont need to be tested by other APIs

**Comment by bsrikan** [comment]
Closing as not a bug

**Comment by grechaw** [comment]
note that unless an issue has 'severity' and 'status', it never gets to bugtrack at all, so you can just close this here with github.
