### ISSUE TITLE
Proposed change to TDE, constrain version

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#252]
Right now, the OOTB template from extraction-template-generate matches all instance data. It might be very useful to add a predicate to the top-level context that limits the version and schema name.

With this change in place, it's more likely that a users's TDE will scope only to instance data, and not index values of different types or versions. 

I discovered this issue in working with instance data that has been duplicated during a mock migration. Without the version info, cross products appear in views, because indexing and cardinality are affected.

**Comment by grechaw** [comment]
The change would be to the <context/> line at the top of TDE.

now:

`<context>//es:instance</context>`

after

`<context>//es:instance[es:info/es:version= "version-of-model"]</context>

**Comment by grechaw** [comment]
This is really the appropriate fix to #246 and it indeed fixes that issue.  Moving ahead with a PR.

**Comment by bsrikan** [comment]
Latest QA PR 254 includes tests for this issue. Will ship after the code is merged and the test had run once successfully in regression.

**Comment by bsrikan** [comment]
Test running OK in regression. Shipping the bug.
