### ISSUE TITLE
Migrate to XMLUnit 2.0

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#256]
Non-trivial task to update tests to use XMLUnit 2.0.

https://github.com/xmlunit/user-guide/wiki/Migrating-from-XMLUnit-1.x-to-2.x

**Comment by grechaw** [comment]
Initial upgrade looks successful.  It's a big patch but a nice thing to keep current.  I'll set to fix, continue to verify the patch, and submit for inclusion.

**Comment by grechaw** [comment]
I think in the process of migration I've hit upon the bug that @bsrikan found in #303

**Comment by grechaw** [comment]
more changes coming that will fix the functional tests i think.

**Comment by bsrikan** [comment]
migration to xmlunit2.0 working OK and doesnt break unit or functional tests. Shipping the issue.
