### ISSUE TITLE
Docs: Entity Services Dev Guide - Chapter 2 - Typos

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#257]
* **Issue1:**
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_94014
point 5 in "Optional: Create a Content Database":
Actual:
"Copy and paste the following code into the new query. This code creatse a forest and a database, and then attaches the forest to the database."
Expected:
"Copy and paste the following code into the new query. This code creates a forest and a database, and then attaches the forest to the database."

* **Issue2:**
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_73678
point 4. Since we have created a database named "es-gs" I think it is better to ask readers to select "es-gs" than "your content database" every where in the document. Please let me know what you think.
Actual:
"Select your content database from the Database dropdown."
Expected:
"Select "es-gs" database from the Database dropdown."

* **Issue3:**
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_76701
point 8
Actual:
"Optionall, click the Explore button at the top of the query editor to view the JSON version of the descriptor."
Expected:
"Optionally, click the Explore button at the top of the query editor to view the JSON version of the descriptor."

* **Issue4:**
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_32701
This is more of a suggestion than issue. Can we mark below text as information (i), where (i) stands out similar to what we have in 
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_43291
"Production applications can require many other types of customizations. For example, you might need to normalize a date value, perform a more sophisticated type conversion, or extract the value of a property from somewhere other than the source data."

* **Issue5:**
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_32701
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_90501
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_pgfId-1117467
Replace instances of "title:" with "namespace:" for all "title:extract-instance-T" and "title:instance-to-envelope"

* **Issue6:**
http://pubs.marklogic.com:8011/9.0/guide/entity-services/getting-started#id_90501
Add import statement of module namespaces to below snippets
`title:instance-to-envelope(
  title:extract-instance-T($source))` 
  and 
    `  let $instance := person:extract-instance-Person($source)`
    `  ...`
    `  return xdmp:document-insert(`
    `  $uri,`
    `  person:instance-to-envelope($instance),`
    `  ...)`

**Comment by kcoleman-marklogic** [comment]
Issue #2: This is deliberate. You are not required to use that database, so I don't tell you to use that database.

Issue #4: I chose not to give this Info block formatting, but I did move the paragraph closer to the top of the topic where it is less likely to be overlooked. I don't think it needs to be heavily emphasized. This is just the GS.

Issue #5: I chose not to change this, beyond change it from "title" to "modeltitle" and mentioning the ns prefix is derived from the model title. 

Issue #6: The import is not required, IMO, and only adds noise. This text is an explanation of the runnable code that appears above it. The runnable code includes the import. Those code snippets merely illuminate the discussion and are not meant to be runnable.

**Comment by bsrikan** [comment]
Thanks Kim for your feedback.

**Comment by kcoleman-marklogic** [comment]
As I mentioned on the other doc bug, if you don't have time, you can punt verifying this, and it's also OK if you don't get to it for awhile. 4/15 is soon enough for me to get in any additional corrections.

**Comment by bsrikan** [comment]
Looks good. Shipping.
