### ISSUE TITLE
Docs: Entity Services Dev Guide - Chapter 1 - Typos

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#258]
* **Issue#1** ==> Typo in Terms and Definitions section as below
Actual:
"This material in this guide assumes the reader if familiar with the following terms and definitions:"
Expected:
"The material in this guide assumes the reader is familiar with the following terms and definitions:"
    
* **Issue#2** ==> Typo in Why Use Entity Modeling section just above Modeling Pipeline chart as below
Actual:
"Using the Entity Services API, you can capture your modeled entity types, properties, and relationsips in a model descriptor, and then use the descriptor create a model."
Expected:
"Using the Entity Services API, you can capture your modeled entity types, properties, and relationships in a model descriptor, and then use the descriptor to create a model."  
    
* **Issue#3** ==> Typo in Application Scaffolding section
Actual:
"Model Schema: An XML schema derived from the model. Useful for validating entity instances such as you might receive from a downstream client application."
Expected:
"Model Schema: An XML schema derived from the model. Useful for validating entity instances that you might receive from a downstream client application."

* **Issue#4** ==> Typo in Next Steps section
Actual:
"Getting Started With Entity Services: Walk through a simple example of creating a model, harmonizing data, creating enveloping documents, and searching entity instances."
Expected:
"Getting Started With Entity Services: Walk through a simple example of creating a model, harmonizing data, creating envelope documents, and searching entity instances."

* **Issue#5** ==>
Actual:
"Exploring the Entity Services Open-Source Examples: Explore several end to end example applications built with Entit Services."
Expected:
"Exploring the Entity Services Open-Source Examples: Explore several end to end example applications built with Entity Services."

* **Issue#6** ==> 
Next Steps section have "Exploring the Entity Services Open-Source Examples" link listed last but that is the first document. Is that intentional?

**Comment by kcoleman-marklogic** [comment]
I believe I took care of all of these, @bsrikan, so I am handing this back to you for verification. Issue 6 is intentional, so I did not make a change there. 

If you feel you don't have time to check these changes, that's fine - you can just ship it. It's not the end of the world if we miss one of these. :) Also, from my perspective, you don't have to verify the changes by 3/15. More like 4/15.

**Comment by bsrikan** [comment]
Verified changes to the docs. Shipping.
