### ISSUE TITLE
Version example README expand

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#262]
The README for the version example should have more inputs/outputs and an explanation of what's going on for each.  I'd intended to do this but did not complete it, as the running of the example does not clearly indicate what's happening in each transitional state.

**Comment by grechaw** [comment]
This is my most important task to complete for today

**Comment by grechaw** [comment]
probably ready to ship, to you for judgement @bsrikan

**Comment by bsrikan** [comment]
Looks good. Shipping.
