### ISSUE TITLE
schema-gen() returns different results for xml and json when an entity type has duplicate property name

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#263]
This issue was found when testing #212 .

Sample doc: Attached a zip file

Query:
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';

es:schema-generate( es:model-validate(doc('invalid-bug43212.json'))),
es:schema-generate( es:model-from-xml( fn:doc( 'invalid-bug43212.xml')))

[Test Input file.zip](https://github.com/marklogic/entity-services/files/818201/Test.Input.file.zip)
[Test Input file.zip](https://github.com/marklogic/entity-services/files/818202/Test.Input.file.zip)

Issue:
With JSON input file schema-gen() returns an additional comment as below:
```
<!--
XSD schemas prohibit duplicate element names. This element is commented out because it conflicts with another of the same name.
 <xs:element name="OrderID" type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema"/> 
-->
```

**Comment by bsrikan** [comment]
NOTE to self: Uncomment schema-gen() test for json input file once bug is fixed.

**Comment by grechaw** [comment]
Duplicate properties are confusing not just for entity services -- I don't think we should try to do anything here.

I would have thought so, but try this:

```
let $a := json:object()=>map:with("a", "b")=>map:with("a", "c")

let $n1 := xdmp:unquote('{"a":"b", "a": "c"}')
let $n2 := object-node { "a" : "b", "a": "c"}
let $b := xdmp:from-json($n1)
let $c := xdmp:from-json($n2)

return ($a, $b, $c, $n1, $n2)
```

It seems JSON nodes can have duplicate keys which is fine, but if you make a json:object out of them, then each key will ever only have one value, even if it looks like there are two items in the map.

**Comment by grechaw** [comment]
not entirely clear what to do for this bug, and it's impact is minimal, so set to 9.0-2 to provide stability for release target.

**Comment by grechaw** [comment]
I discussed this issue with some members of the team and we agree it's in the 'garbage in garbage out' class of bugs.  We cannot account for the foibles of map/json implementation on the server.
