### ISSUE TITLE
in-memory instances and json canonical instances are missing type info.

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#264]
I found this issue when reviewing the documentation.  I think that this library requires a change before we ship 9, as behavior does not match future state for json envelopes, and also does not

Right now, the two functions

es:instance-from-document
and
es:instance-json-from-document

retrun the same structure, and they have no type information.  To better integrate these functions with how extract-instance works, they should be valid inputs.

For this envelope

```
import module namespace es = "http://marklogic.com/entity-services" at "/MarkLogic/entity-services/entity-services.xqy"; 

let $e := document { <es:envelope xmlns:es="http://marklogic.com/entity-services">
    <es:instance>
      <es:info>
        <es:title>Person</es:title>
        <es:version>0.0.1</es:version>
      </es:info>
      <Person>
        <id>1234</id>
        <firstName>George</firstName>
        <lastName>Washington</lastName>
        <fullName>George Washington</fullName>
      </Person>
    </es:instance>
    <es:attachments>
      <person>
        <pid>1234</pid>
        <first>George</first>
        <last>Washington</last>
      </person>
    </es:attachments>
  </es:envelope> }
  
return (es:instance-json-from-document($e), es:instance-from-document($e))
```

Should return these:

```
{
"Person": {
"id": "1234", 
"firstName": "George", 
"lastName": "Washington", 
"fullName": "George Washington"
}
}
json as
{
"$type": "Person", 
"id": "1234", 
"firstName": "George", 
"lastName": "Washington", 
"fullName": "George Washington"
}
```

but both these functions return a flat structure without $type.

**Comment by grechaw** [comment]
@kcoleman This is what I just I just discovered while reviewing the docs.  I think it's an important change to make, as our JSON will be XPath-parity with XML, while the in-memory instance is a flat structure

**Comment by kcoleman-marklogic** [comment]
So now we have the following representations of an instance, is that correct?
* with $attachments and $type
* with $type
* without $type and $attachments
When is one expected to use the representation that contains $type? (the second in the list above)

**Comment by grechaw** [comment]
How about

* with $type for the in-memory instance (json:object, JavaScript object)
* with named root for JSON node

$attachments is an ephemeral place to keep source/raw data in extractions.  It gets put into an envelope, but outside of the JSON or XML node representations of an instance.

One thing that should be in the post-9 entity services vocab is 'root' vs' non-root types.  Probably only root types will ever have $attachments.  By "root" I mean those type defs which are stored as documents, rather than within other entity instances.

**Comment by grechaw** [comment]
OK Spec has been updated, and this fix is into a branch.  Making PR now.

**Comment by bsrikan** [comment]
Is this an OK result for results that have $ref in it: 
```
{
"OrderID": "10254", 
"CustomerID": "10254", 
"OrderDate": "1996-07-11T08:19:58", 
"ShipAddress": "Hauptstr. 31", 
"OrderDetails": [
{
"productID": {
"$type": "Product", 
"$ref": "24"
}, 
"unitPrice": "3", 
"Quantity": "15"
}
]
}
```
gets converted to below with this change:
```
{  
  "Order":{  
    "OrderID":"10254",
    "CustomerID":"10254",
    "OrderDate":"1996-07-11T08:19:58",
    "ShipAddress":"Hauptstr. 31",
    "OrderDetails":[  
      {  
        "OrderDetail":{  
          "productID":{  
            "Product":[  
              "24",
              {  

              }
            ]
          },
          "unitPrice":"3",
          "Quantity":"15"
        }
      }
    ]
  }
}
```

**Comment by grechaw** [comment]
no that's still a bug

**Comment by bsrikan** [comment]
Updated keys

**Comment by bsrikan** [comment]
Working as expected post fix. Shipping!
