### ISSUE TITLE
REGR: Unit test TestExtractionTemplates.xml fails

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#271]
TestExtractionTemplates.xml unit test started diffing today:

https://regr-status.marklogic.com/platform/diff?area=server&branch=b9_0&platform=linux-64-rh7v-cluster&date=2017-03-10&diff=TEST-com.marklogic.entityservices.tests.TestExtractionTemplates.xml

Snapshot of the error:
`com.marklogic.entityservices.tests.TestEvalException: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at eval: Internal Server Error. Server Message: TDE-NOSCHEMADB: tde:validate(()) -- No schema database for TDE resource: no schema database configured for current database`

Can you please look into it.

**Comment by grechaw** [comment]
created bug 45034 for Fayez to weigh in on.
If he pushes back on a fix, I'll have to re-work how I validate extraction template, probably by simply using tde:template-insert which was not available when we started work on ES.

**Comment by grechaw** [comment]
I reworked the unit tests to avoid this issue.  It is new behavior from when schemas database defaults changed.

**Comment by grechaw** [comment]
Fix to test in PR.

**Comment by bsrikan** [comment]
Unit tests have run OK on all platforms. Shipping the bug.
