### ISSUE TITLE
Docs: Issues in Chapter 4

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#281]
Issue1:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_16594
Missing a space
`Both theXQuery (es:*) `

Issue2:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_16594
Under description for es:database-properties-generate
Actual:
suitable for with the REST Management API or ml-gradle. 
Expected:
suitable with the REST Management API or ml-gradle. 

Issue3:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_10346
Typo. 
Actual:
An instance converter is a key part of an model-driven application.
Expected:
An instance converter is a key part of a model-driven application.

Issue4:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_18053
Typo.
Actual:
For example, suppose the model contains a 'Name' entity type, with entity propertys 'first', 'middle', and 'last'.
Expected:
For example, suppose the model contains a 'Name' entity type, with entity properties 'first', 'middle', and 'last'.

Issue5:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_43330
Typo.
Actual:
The module can contain additional functions, but these are use internal to the translator module.
Expected:
The module can contain additional functions, but these are used internal to the translator module.

Issue6:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_67998
Use case for Property in Target Only. Handling section says `You might modify the code to assign a meaningful default value or extract the new value from the raw source in the attachments of the source envelope.` While there is an example of default value, it is missing extracting new value from raw source. Here is how I have done it in my e2e:
`=> map:with('rating', xs:float($source-node/root()//es:attachments/Person/rating))`

Issue7:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_67998
Typo in Rename a Property use case.
Actual:
Modify it pull the value from the 'firstName' property of the source:
Expected:
Modify it to pull the value from the 'firstName' property of the source:

Issue8:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_67998
Typo in Entity Type Added to Target Model.
`A conversion function is generated that copies properties from source to target as if there are no differences.`
We dont copy properties from source in this case since the entity type is not there in source. Maybe we should re-word this and say the function looks same as the one that instance converter generates for that type ?

Issue9:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/codegen#id_67998
Typo in use case Property Type Change from Atomic to Array Type
We should add comment as other use cases have from the codegen; like 
`(: Warning: potential data loss, truncated array :)`

**Comment by kcoleman-marklogic** [comment]
OK, here is the change I made related to Issue 8, following our discussion. See if you like it better. And don't be afraid to say no and make me try again. :)

>A conversion function is generated that copies properties from the input source node to the output instance as if there are no differences.

I made the same change to next entry in the table, which was using the same terminology.

**Comment by bsrikan** [comment]
Thanks Kim for hearing me out. This looks good.
