### ISSUE TITLE
Entity Services-ELS Integrated Demo

### ISSUE THREAD

**Issue by cvbmilani** [marklogic/entity-services#287]
Given a source like this

```xml
<policy>
    <client-information>
      <name>Paul</name>
      <address>999 Broadway St</address>
      <phone>323-344-1555</phone> 
      <country>US</country>
      <ssn>999-999-5664</ssn>
      <income>44,4444</income>
    </client-information>
    <policy-information>
      <property-type>Home</property-type>
      <premium>432</premium>
      <asset-value>750,000</asset-value>
      <currency>Dollar</currency>
    </policy-information>
  </policy>
```

I would like to use Entity Services to generate the following document. Note the calculated SSN field, and the attributes
```xml
<es:envelope xmlns:es="http://marklogic.com/entity-services">
  <es:instance>
    <es:info>
      <es:title>policy</es:title>
      <es:version>1.0</es:version>
    </es:info>
    <T>
	
<client access="ID_read">
 <name >Paul</name>
 <address>999 Broadway St</address>
 <phone>323-344-1555</phone> 
 <country>US</country>
 <ssn>XXX-XX-5664</ssn>
</client>
<client access="Compliance">
  <ssn>999-999-5664</ssn>
</client>
<client access="Risk">
  <income>44,4444</income>
</client>
<info access="Risk">
 <property-type>Home</property-type>
 <premium>432</premium>
 <asset-value>750,000</asset-value>
 <currency>Dollar</currency>
</info>
    </T>
  </es:instance>
  <es:attachments>
<policy>
    <client-information>
      <name>Paul</name>
      <address>999 Broadway St</address>
      <phone>323-344-1555</phone> 
      <country>US</country>
      <ssn>999-999-5664</ssn>
      <income>44,4444</income>
    </client-information>
    <policy-information>
      <property-type>Home</property-type>
      <premium>432</premium>
      <asset-value>750,000</asset-value>
      <currency>Dollar</currency>
    </policy-information>
  </policy>
</es:attachments>
</es:envelope>`

```

By going this, I can use ELS to create 4 roles
•	sec.createRole("Reader","ID_read",null, null, null);
•	sec.createRole("ID_read","ID_read",null, null, null);
•	sec.createRole("Compliance","Compliance",null, null, null);
•	sec.createRole("Risk","Risk",null, null, null);

create 3 users: CallCenter, Risk Risk Officer, Compliance Admin 

•	sec.createUser("CallCenter","CallCenter","password",["Reader","ID_read"],null,null);
•	sec.createUser("Financial_Risk_Officer","Financial Risk Officer","password",["Reader","Risk"],null,null);
•	sec.createUser("Compliance_Admin","Compliance Admin","password",["Reader","ID_read","Risk","Compliance"],null,null);

Create protected paths
•	sec.protectPath("//client[access='ID_read']", null, xdmp.permission("ID_read", "read", "element")),
•	sec.protectPath("//client[access='Compliance']", null, xdmp.permission("Compliance", "read", "element")),
•	sec.protectPath("//client[access='Risk']", null, xdmp.permission("Risk", "read", "element")),
•	sec.protectPath("//info[access='Risk']", null, xdmp.permission("Risk", "read", "element"))

And get different outputs for fn.docs when each different user queries, such as the CallCenter user sees the masked SSN, the Risk Officer sees no PII, etc.

**Comment by grechaw** [comment]
The approach to making this canonical document would be a little different than what you have.  Entity Services is very opinionated about how the document is created from type and property information.  So if it looked more like the following, would that still work?  Type types in the model are Client and Info in this case.  The wrapping <T> that you have above could be used too.  These changes just reflect convention for the feature

```
 <Client access="ID_read">
 <name >Paul</name>
 <address>999 Broadway St</address>
 <phone>323-344-1555</phone> 
 <country>US</country>
 <ssn>XXX-XX-5664</ssn>
</Client>
<Client access="Compliance">
  <ssn>999-999-5664</ssn>
</Client>
<Client access="Risk">
  <income>44,4444</income>
</Client>
<Info access="Risk">
 <propertyType>Home</propertyType>
 <premium>432</premium>
 <assetValue>750,000</assetValue>
 <currency>Dollar</currency>
</Info>
```

Making this happen with today's feature would be a matter of customizing the extraction functions in the instance converter.  You might make four copies of an extraction function to make the different versions of 'Client',

These structures would work better with entity services if you just make @access another property.  We avoided attributes in the design.  The paths you wrote look like they're using properties anyway rather than attributes.

This is not enough information to actually build what you're looking for, but it's some things that occurred to me in seeing it.

**Comment by grechaw** [comment]
We didn't manage to go 100% with this example for MarkLogic world, but can come back to it.  I'll put this issue into triage in 9.0-3 timeframe, for us to discuss in a feature group meeting.

**Comment by grechaw** [comment]
I've started work on an ELS-integration recipe and will be looping back with @cvbmilani and @jmakeig about it next week.

**Comment by grechaw** [comment]
back on track getting Justin's feedback incorporated.

**Comment by grechaw** [comment]
I'll have a working example and PR today I think.

**Comment by grechaw** [comment]
sending to @bsrikan pending review.  In a new PR today.

**Comment by jmakeig** [comment]
Is there a PR where I can provide feedback? The two above are from September.

**Comment by grechaw** [comment]
Hi Justin, it just looks that way because I merged new work into an old commit and did a git push -f.


Probably something to avoid in the future.



Charles Greer
Lead Engineer
MarkLogic Corporation
cgreer@marklogic.com
Cell:  +1 707 318 0442
@grechaw
www.marklogic.com

________________________________

**Comment by jmakeig** [comment]
Everyone’s staring at me because I literally laughed out loud. Yes, please do not force push on shared branches. 

Is there a commit(s) I can look at then? I’d like to better understand the approach, especially to guide our future plans with entity models as the place to hang policy.

**Comment by grechaw** [comment]
git push -f on a PR is perfectly appropriate, IMO

the commit is good to look at, it's the timestamp that is misleading.

**Comment by jmakeig** [comment]
> `git push -f` on a PR is perfectly appropriate, IMO

Agreed 100%. I thought you were talking about something that had already been merged.

**Comment by grechaw** [comment]
It occurred to me that @cvbmilani might want an explicit link to the branch too.

https://github.com/grechaw/entity-services/tree/els-recipe/entity-services-examples/example-els

I'll have some more edits, would like to know whether the example is something like you had in mind Ciao

**Comment by grechaw** [comment]
In addition to good feedback for README, @bsrikan noted I don't demonstrate query rolesets here.

Now that I know what they are I will add to the example.

**Comment by grechaw** [comment]
In addition to good feedback for README, @bsrikan noted I don't demonstrate query rolesets here.

Now that I know what they are I will add to the example.

As it stands, what's protected is *seeing* the path.  However, without an extra step, queries across the board cannot see the values from the protected path.  One must add query rolesets to the configuration in order for a privileged user to be able to search on the values in the protected path.

**Comment by grechaw** [comment]
I've added query rulesets to the example.
I should say that the experience of adding ELS configuration was low-level and straightforward, but it still took me quite some time and effort to do it.  We could really improve tooling and data management for this feature significantly.

**Comment by grechaw** [comment]
@bsrikan , I've added query rolesets to the example.   Back to you for verification.

**Comment by bsrikan** [comment]
Verified and this looks good. Searching for the pii after adding query rolesets works for users having privilege to read the pii.

@grechaw 
Should I pass this issue to @cvbmilani for verification or ship it?

**Comment by bsrikan** [comment]
Shipping the issue.

**Comment by grechaw** [comment]
Thanks @bsrikan ! I think that's a wrap for 9.0-4
