### ISSUE TITLE
Remove tdex extension from examples

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#288]
Although we cannot make this change until ml-gradle releases a change for https://github.com/rjrudin/ml-gradle/issues/192, this issue is to remind us to change examples to not rely on the `tdex` extension anymore for deploying extraction templates.

**Comment by grechaw** [comment]
Taking a look now about updating ml-gradle to use the new TDE directory structure.

**Comment by grechaw** [comment]
I've updated example code to make this change, and verifies it all works with an ml-gradle upgrade.

**Comment by grechaw** [comment]
committed to develop and b9_0 branches

**Comment by rashiatmarklogic** [comment]
Lets sync up on this next week, I need to understand what needs to be done here.

**Comment by grechaw** [comment]
OK, this is actually a really simple verification I think, amounts to "no regression".
The change is that PM didn't want me to encourage use of "tdex" to mark extraction templates.  So @rjrudin changed ml-gradle to load extraction template from a directory under ml-schemas, and allows them to have the extension ".xml".  So this change goes through the examples, and puts all TDEs into a 'tde' folder and renames them with the .xml extension.

I verified that ml-gradle does the right thing.  If you verify for sanity purposes that examples still work that's all that's needed.
