### ISSUE TITLE
ES example nomenclature (minor)

### ISSUE THREAD

**Issue by matt-turner** [marklogic/entity-services#293]
Hi - when going through the examples I got tripped up after generating the instance converter when the example nomenclature changed from person-0.0.1.* to person-1.0.0 and sometimes person-3.0.0.

Here is what I see on: http://docs-ea.marklogic.com/guide/entity-services/codegen

- version translator uses person-1.0.0 to person-1.0.0.
- TDE starts with person-1.0.0 but the full sample code goes back to person-0.0.1.
- schema uses person-1.0.0
- database config uses person-3.0.0
- search options start with person-0.0.1 but go uses person-1.0.0 in the full code

I get that these are all technically correct - but it would be good to standardize and be consistent especially since the entire framework relies on file name consistency as you from one step to another.

Also - maybe just one . version? person-0.1?  :)

Thanks,

Matt

**Comment by kcoleman-marklogic** [comment]
You are 100% correct. I recently filed a similar bug (internally) in response to similar review feedback. It is scheduled for 9.0-2.

I'll let Justin decide whether to leave this open or not. From my perspective, it's a dup of an existing bug. The related changes will be tracked internally, not on GitHub. The internal number is 45603.

**Comment by kcoleman-marklogic** [comment]
Oh, and you'll have to take the x.y.z versions up with Charles and Justin. That's a convention they push.

**Comment by grechaw** [comment]
It looks like there is some inconsistency that needs to be addressed.  I'll put it in the 9.0-2 buglist, I'll try to take a look at it next week though and hopefully push changes at least to develop branch.

**Comment by kcoleman-marklogic** [comment]
The versioning inconsistency is in the dev guide, not your examples, Charles, so that's on me. At least, AFAIK. :) That bugtrack bug is filed against me. 

So unless you were version-sloppy in your examples, too, I think the only thing you need do is cogitate about semver insistence vs not, and let me know what you decide about that.

**Comment by grechaw** [comment]
Ah! OK, thanks Kim.

I think that, indeed, we want folks to just get used to looking at semver.  The jury's out on whether the notions of change in models map exactly to those of codebases, but I've seen data versioned with three points for a long time now, even if it's overkill for the examples.

**Comment by jmakeig** [comment]
For what it’s worth, in speaking with a customer yesterday, without prompting, his examples of schema (model) versioning all used semver. That’s one data point to support this direction. This is something we should validate further.

**Comment by grechaw** [comment]
@kcoleman-marklogic this issue is probably not on your radar at all as it's hidden over here in github.  Do you want to update it?  It's set for 9.0-2, which is why I'm asking.

**Comment by kcoleman-marklogic** [comment]
I think I took care of most of this for 9.0-3 (or maybe it was 9.0-2, IDK). You're right, though: It never made it's way into bugtrack (yay, integration fail), so wasn't on my radar. Will review for 9.0-4 and update this issue appropriately.
