### ISSUE TITLE
Verbose comments in generated artifacts may actually reduce usability

### ISSUE THREAD

**Issue by jmakeig** [marklogic/entity-services#297]
From #232, @grechaw,
> “In reviewing codegen with @matt-turner yesterday, I think that the extensive use of comments in the XQ modules is wrong-headed. I end up just deleting it all anyway when I use entity services, and it may get in the way of having clearly readable code, rather than comments. There's a balance to be struck, of course, but I'd like to float replacing the very long comment blocks with, say, a link to documentation.”

**Comment by bsrikan** [comment]
Test updates in PR #310. Will ship after successful regression run

**Comment by bsrikan** [comment]
Shipping the issue.
