### ISSUE TITLE
Are we handling hyphens appropriately in property and type names?

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#298]
We advocate `CapitalCamelCase` for type names and `lowerCamelCase` for property names in Entity Services, which aligns with RDF and Java practices.  Hyphens are not prohibited, however. 

This issue is to check to see what happens with TDE and hyphens.  I know that hyphens are not allowed as column names or view names, but do not know what steps to mitigate or protect.

One proposal would be to substitute underscores for hyphens for TDE.  Another would be to prevent hyphens in validation.

**Comment by kcoleman-marklogic** [comment]
You probably know this already, but here is some info I got from Francisco when we tripped over the hyphen this while you were gone:

>View/schema/column names all follow the same rules. The best documentation I can find is here:
https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers

It's all a bit of a tangle, but when I read it, I thought the intersection between this and let's call them "XQuery habits" was only like to collide over hyphens.

**Comment by grechaw** [comment]
So the question for the WG will be -- should we catch and transform invalid column names, or leave them as-is for the developer to rationalize.

**Comment by jmakeig** [comment]
I think we should do this. I would expect any TDE the Entity Services generates to be (at least) valid, out-of-the-box. That doesn’t mean the developer won’t have to do some rationalization, it’s just that we’ll get her over the “invalid” hump.

See also customer feedback from @derms about TDE (albeit sans ES) on-boarding experience.

**Comment by grechaw** [comment]
There is a deeper way to consider the issue.  Note that entity services, by convention, prefers:

CapitalizedCamelCase for entity type names, and 
lowercaseCamelCase for property names.

Note that if entities enforced this, or internally canonicalized names, then there would not be hyphens in them.  But we chose not to enforce names.

Internally, MarkLogic knows about camelCase vs. hyphenation, viz the Entity Services API in JavaScript, which materializes as if by magic from the XQuery.  It seems as though we have some as-yet unexposed primitive around naming things in MarkLogic, and it may do us well to dissect that before making arbitrary mappings.

If we just asserted that names in entity services have to conform to a certain shape, we'd be done.  If we have to accommodate for getting rid of hyphens, and having slightly different domains for SQL/Optic vs. JSON/XML names, that might bite us later.

**Comment by grechaw** [comment]
That said, Daniel had a good point.  Why don't we just make TDE more lenient wrt column names?

**Comment by jmakeig** [comment]
> Why don't we just make TDE more lenient wrt column names?

Because SQL92?

**Comment by grechaw** [comment]
That's not a reason, that's a rationalization.  Optic could handle column names with hyphens, and our SQL engine could as well.  But if that's the end of that line of reasoning, then we can just turn this into a bug and move forward with a TDE column name mapping.  It won't affect anybody wrt compatibility.

**Comment by grechaw** [comment]
I'll fix this while trying to deliver new functionality in 9.0-3 timeframe

**Comment by grechaw** [comment]
We have decided just to replace hyphens with underscore, 

That is, in those cases where a property has a hyphen, the corresponding column name will have an underscore

this-column =>  this_column

**Comment by grechaw** [comment]
This is in progress now, I've modified some of my test cases to include hyphens so as to cover this change in units.

**Comment by bsrikan** [comment]
Is this change applicable only to column names? I have a test testExtractionTemplatesRequired() where <schema-name> having "-" was also changed to underscore. Is this expeted?

**Comment by grechaw** [comment]
Indeed, schema, view, and column names all have this issue.
Needs to be explicit in the docs too, I'll check

**Comment by kcoleman-marklogic** [comment]
Bit too soon to check the docs since they haven't been changed since 9.0-1. :)

But, yes, it needs to be explicitly called out. Along with removing the stricture against hyphens that is currently in there.

**Comment by grechaw** [comment]
Since this was treated as a bugfix for the original design, I updated entity-services.md spec with the following note:

```
* Note: In 9.0-3, there is a mapping to avoid invalid schema, column, and view names.  If
the name of a model, type, or property has a hyphen in it, then the corresponding TDE
schema, view, and columns will have that hyphen replaced with an underscore, in order to
avoid invalid SQL names.
```

I've antipathy against removing the stricture.   Mapping are not great -- they are harder to understand and maintain.  Avoiding hyphens would avoid ever getting into an issue where you have to know two different forms of a name for, say, Optic queries and cts:search

**Comment by kcoleman-marklogic** [comment]
I agree that it is not a good idea and we should advise against it. However, I think that's different from something like this, which is what we say now:

> If you plan to generate a TDE template from the model, the title must also be a valid SQL view name, contain no special characters except underscore ('_'); for details, see Naming the View in the SQL Data Modeling Guide.

That's just plain not true now.

**Comment by grechaw** [comment]
Got it

**Comment by bsrikan** [comment]
Issue is fixed now. Added a test that verifies the fix. 
Assigning to Kim to make documentation changes.

**Comment by kcoleman-marklogic** [comment]
Documentation updated.
