### ISSUE TITLE
Error in executing Entity Services Examples

### ISSUE THREAD

**Issue by GayatreeT** [marklogic/entity-services#299]
Hi,

I'm trying to run one of the examples for entity services - it tries to download the gradle 3.1 distribution and fails. The build does not go beyond that point. I have Gradle 3.1 installed.
Attached is the error message (it times out). I've tried setting the proxy too - maybe those settings are wrong? Please advise. 
![error](https://cloud.githubusercontent.com/assets/20122171/26329085/85eba2a6-3f13-11e7-95fc-a13e51a79f7f.PNG)

Lines added to gradle.properties: 
systemProp.https.proxyHost=<myhostname>
systemProp.https.proxyPort=8080

**Comment by grechaw** [comment]
You'll need direct access to the internet to run these examples.  We don't have experience running behind a proxy, but you would have the same issue with any other gradle-based project.

Have you succeeded in running another project?  Can you ping `services.gradle.org` ?

**Comment by GayatreeT** [comment]
Hi Charles,

Thanks for getting back to me.
Right, the services.gradle.org ping also times out.


Regards,
Gayatree

**Comment by GayatreeT** [comment]
However, I set the proxy in gradle.properties – it still times out..

From: Tiwari, Gayatree
Sent: Monday, May 22, 2017 5:31 PM
To: 'marklogic/entity-services'
Subject: RE: [marklogic/entity-services] Error in executing Entity Services Examples (#299)

Hi Charles,

Thanks for getting back to me.
Right, the services.gradle.org ping also times out.


Regards,
Gayatree

**Comment by grechaw** [comment]
If you need to use a proxy, then it will be a host and port provided you by your system administrator.  These values need, in other words, to be filled in by you on the advice of a colleague

```
systemProp.https.proxyHost=
systemProp.https.proxyPort=8080
```

This issue really doesn't have anything to do with our project, but if there is some documentation we should reference for devs in your situation, perhaps we can include that in a README?

**Comment by GayatreeT** [comment]
Yes, Charles, I did use the proxy host and port number for our network.

Yeah it’s probably not directly about the project, but I figured the people connected with it would be the ones to contact. Sorry, I tried emailing first coz I didn’t want to open an issue, but I was redirected to this & stackexchange.
Anyway, I tweaked some things and it did install last night.
Thanks!


Regards,
Gayatree

**Comment by GayatreeT** [comment]
P.S. Re: documentation: Yeah, if you’d like to add that people behind a firewall would need to set some proxy settings, you can add that.

From: Tiwari, Gayatree
Sent: Tuesday, May 23, 2017 8:04 AM
To: 'marklogic/entity-services'
Subject: RE: [marklogic/entity-services] Error in executing Entity Services Examples (#299)

Yes, Charles, I did use the proxy host and port number for our network.

Yeah it’s probably not directly about the project, but I figured the people connected with it would be the ones to contact. Sorry, I tried emailing first coz I didn’t want to open an issue, but I was redirected to this & stackexchange.
Anyway, I tweaked some things and it did install last night.
Thanks!


Regards,
Gayatree

**Comment by grechaw** [comment]
OK, looking forward to feedback and more issues, glad you got the proxy working @GayatreeT
