### ISSUE TITLE
Bubble up private code gen methods to make integration easier (see Data Hub).

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#301]
Some functions required for extraction are currently included as private functions with code-generated modules.  It would be more convenient to work with entity services from the data hub perspective were these functions part of the es:module.

Propose removing two functions from instance converter and two functions from version translator.

instance:init-source => es:init-source
instance:add-attachments => es:add-attachments
translator:init-source => es:init-translation-source
translator:copy-attachments => es:copy-attachments

also to add
es:init-instance which replaces some inline code currently in the codegen modules.

**Comment by grechaw** [comment]
I have this work ready to review by @paxtonhare .

It will require docs work, as the public interface is slightly changed.  Also I'd like review to make sure these functions make sense, that they are indeed useful and should be exposed.

**Comment by grechaw** [comment]
Hi @bsrikan this issue should go to Kim next, as it is largely a documentation task.

**Comment by bsrikan** [comment]
Test updates are checked in #310. Passing it on to Kim for documentation.

**Comment by kcoleman-marklogic** [comment]
Apidoc for these functions has already been added. You can find them pubs, under the "Helper Functions" subcat of the ES apidoc. Charles has reviewed them, so I think we close this task out.
