### ISSUE TITLE
extract-instance-X() is missing a property that is an array of external references

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#303]
Test Class: TestEsConversionModuleGenerator
Test Name: testInstanceToCanonicalXml()

XQuery being executed:
`
import module namespace ext = 'http://refCombo#Northwind-Ref-Combo-SameDocument-SubjectIri-0.0.1' at '/conv/valid-ref-combo-sameDocument-subIri.xqy';`
`ext:instance-to-canonical-xml(ext:extract-instance-Order( doc('10248.xml') ))
`

extract-instance-Order() of the generated module "/conv/valid-ref-combo-sameDocument-subIri.xqy" has an es:extract-array() that looks like:
`let $OrderDetails  :=             es:extract-array($source-node/OrderDetails/OrderDetails, es:init-instance(?, 'OrderDetails'))`

It has one "OrderDetails" too many. This test was working OK before the refactoring.

Expected Result:
```
<Order>
<CustomerID>
<Customer>VINET</Customer>
</CustomerID>
<OrderDate>1996-07-04T14:25:55</OrderDate>
<ShipAddress>59 rue de l'Abbaye</ShipAddress>
<OrderDetails datatype="array">
<OrderDetails>
</OrderDetails>
</OrderDetails>
</Order>
```

Actual Result:
```
<Order>
<CustomerID>
<Customer>VINET</Customer>
</CustomerID>
<OrderDate>1996-07-04T14:25:55</OrderDate>
<ShipAddress>59 rue de l'Abbaye</ShipAddress>
</Order>
```

**Comment by grechaw** [comment]
good catch.

**Comment by grechaw** [comment]
It's not an extra "OrderDetails" but rather, the ref is pointing to a non-existing type called "OrderDetails".  
I'll come back to you on this one, I think the new result might be better?  Not sure, I'll have to talk with you about it.

**Comment by grechaw** [comment]
Hi Srikanth, I think you did find a bug in here, but also I think that the test has unexpected results.

I"ll make a feature branch for you to take a look at -- I need some consultation in how to proceed.  Part of the issue is that I upgraded XML Unit at the same time, and had to make some choices throughout the codebase as to how to adjust.

**Comment by grechaw** [comment]
It does seem after our conversation that the 'property' step should not be there for references

**Comment by bsrikan** [comment]
Following test in e2e is another example of the bug where it fails to extract ShipAddress which is an array of ShipDetails

```
import module namespace nwind = "http://marklogic.com/test#Northwind-0.0.1" at "/ext/Northwind-0.0.1.xqy";

let $superstore-e := nwind:extract-instance-Superstore(
  doc("/entity-services-e2e/e2e-nwind/data/third-party/csv/superstore.csv-1086.json")
)
return
(
  $superstore-e, nwind:instance-to-envelope($superstore-e)
)
```

**Comment by grechaw** [comment]
I think I finally fixed this issue today, along with the new namespace implementation.  Still have to explore the test surface area to see if I'm missing something.

**Comment by bsrikan** [comment]
Will test once PR #315 is merged to develop.

**Comment by bsrikan** [comment]
Issue is fixed and the functional test runs OK. Shipping the bug.
