### ISSUE TITLE
Aesthetic bugs in entity-services-codegen.xqy

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#304]
Issue1:
Couple of function declarations still take $source as node() as compared to the refactored item()
a>declare function {$module-prefix}:convert-instance-{$entity-type-name}( $source as node() ) as map:map
b>declare function {$module-prefix}:convert-instance-{$removed-entity-type-name}( $source-node as node() ) as map:map

Issue2:
Function declaration within <removed-type> is not closed properly. Although commented, might be a good idea to close all the open braces.

**Comment by grechaw** [comment]
Issue one was requested by Paxton verbally.  I need to get it into the spec as a change and make sure the WG is ok with it.

Issue 2 ill definitely address

**Comment by grechaw** [comment]
These fixes are in my current work in progress.

**Comment by grechaw** [comment]
I'm finally addressing these today

**Comment by bsrikan** [comment]
Verified. Shipping the issue.
