### ISSUE TITLE
Examples person and races not running properly

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#305]
When running person example we get an error as below:
```
Exception in thread "main" java.lang.NullPointerException
        at com.marklogic.entityservices.examples.person.PersonExplorer.table(PersonExplorer.java:100)
        at com.marklogic.entityservices.examples.person.PersonExplorer.runOpticQuery(PersonExplorer.java:221)
        at com.marklogic.entityservices.examples.person.PersonExplorer.main(PersonExplorer.java:265)
:entity-services-examples:runExamplePerson FAILED
```
Model and source docs dont seem to have been inserted

When running races example we get an error as below:
`TDE-INDEX: Error applying template /tde/Race-0.0.1.xml to document /runs/311.xml: TDE-EVALFAILED: Eval for Column runnerName='runByRunner/Runner/name' returns an empty sequence for a non-nullable column . See the MarkLogic server error log for further detail.`

**Comment by grechaw** [comment]
I see what this is -- the examples have their own gradlew script inside the subdirectory.  Relative directory matters when loading configs, so the examples only work with that gradle wrapper, from the examples directory.

The README shows how to run them from there.  I think your config will be correct and the error gone when you retry from within the examples dir.

**Comment by bsrikan** [comment]
All example tests running fine. Missed this bug as it wasnt labelled Test. But this is all good to ship now.
