### ISSUE TITLE
Incoporate generation of JSON envelopes

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#308]
This issue replaces another one that was not well-described.

In 9.0-3, Entity Services will generate JSON envelopes.  This is an API enhancement, and it has been incorporated into a draft of a delta spec.  Tests and implementation are in progress.

**Comment by grechaw** [comment]
This issue is in PR.

**Comment by bsrikan** [comment]
Started testing. Filed a bug #318

**Comment by bsrikan** [comment]
Added tests that will be in PR later today.

**Comment by bsrikan** [comment]
Task complete. Added tests are running fine. Shipping the task.
