### ISSUE TITLE
Property to allow codegen of either element range indexes or path range indexes, per entity type

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#309]
Two new properties are introduced, on each entity type, 

path-range-index  (JSON pathRangeIndex)
and
element-range-index (JSON elementRangeIndex)

path-range-index is equivalent to backward compat range-index, which we will deprecate.

**Comment by grechaw** [comment]
There is some intersection between this task and support for namespaces in XML.

**Comment by grechaw** [comment]
Made significant progress on this issue today, along with namespace support #122 .

Implemented and tests passing for XML/JSON entity types, database properties generation and search options generation.

So the portions of #122 that do not have to do with range indexes are still remaining.

**Comment by grechaw** [comment]
Almost complete, will deliver PR by Monday.

**Comment by bsrikan** [comment]
Started testing. Filed a bug, #317

**Comment by bsrikan** [comment]
Added tests that will be in PR later today

**Comment by bsrikan** [comment]
Task complete. Added tests are running fine. Shipping the task.
