### ISSUE TITLE
Verify JSON XPath expressions for TDE and indexes.

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#314]
At MarkLogic World I found that JSON envelopes required a change to generated TDE templates in order to navigate object node structure.

This task is to track down that difference and account for it in JSON envelopes.

**Comment by grechaw** [comment]
The change had to do with nesting.  JSON envelope required an extra ".." to reference a parent from an embedded instance.  There may be an alternate that will work with both XML and JSON, or this might indicate we should rethink the JSON structure slightly.

**Comment by grechaw** [comment]
I verified that XPath expressions work for single-level entities.  I'm now reviewing the examples and will see how they work for multi-level TDE.

**Comment by grechaw** [comment]
I have found one thing I'd like to fix -- the TDE templates now find the instance context with namespace -- but JSON envelopes have none.  So I need  a TDE which will patch both template types.

**Comment by bsrikan** [comment]
Verified in tests. Will ship this bug after adding e2e test for this issue.

**Comment by bsrikan** [comment]
Test in e2e verified this bug and is working as expected. I indeed had to add a "../" to work with json envelopes for embedded instances. Shipping.
