### ISSUE TITLE
XSD generation for namespace

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#316]
This part of namespace configuration is still not delivered.
XSDs need to be modified when there is a model that has the namespace and namespace-uri properties.

**Comment by grechaw** [comment]
I've got this feature all done now and tests passing.  Will create a PR.  The testing I had to do is slightly non-optimal, but I did cover the case of a model with two namespaces, and hence two imports.

**Comment by bsrikan** [comment]
Task complete. Added tests are running fine. Shipping the task.
