### ISSUE TITLE
instance-to-canonical-json() doesnt return all the items for a property that is an array

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#318]
Below query is from unit test:

```
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import module namespace conv = 'http://marklogic.com/entity-services/test#Order-0.0.4' at '/ext/Order-0.0.4.xqy';

conv:instance-to-canonical-json(conv:extract-instance-Order( doc('Order-Source-1.xml')))
```

There are 2 products in the source document and only 1 is returned. Apparently it seems to have been overwritten so the last product is only returned. 
instance-to-canonical-xml() returns 2 as expected.

EDITED: Updated to instance-to-canonical-json() in place of instance-to-json-envelope()

**Comment by grechaw** [comment]
good catch.

**Comment by grechaw** [comment]
Fixed this too in a PR to be pushed shortly.

**Comment by bsrikan** [comment]
Verified the fix. Working as expected.

**Comment by bsrikan** [comment]
Shipping the issue.
