### ISSUE TITLE
es:instance-get-attachments() doesnt work with json envelopes

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#319]
Query from functional test testInstanceGetAttachmentsJSON()

```
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import module namespace ext = 'http://refSameDocument#Northwind-Ref-Same-Document-0.0.1' at '/conv/valid-ref-same-doc-gen.xqy';

let $sourceDocument := doc('VINET.json')
return xdmp:from-json-string(es:instance-get-attachments(ext:instance-to-json-envelope(ext:extract-instance-Customer( ($sourceDocument)))))

```

Query returns an empty sequence because es:instance-get-attachments() currently doesnt work with instance-to-json-envelope(). 
get-attachments() is looking for '//es:attachments' whereas it should be "//attachments" for json envelopes

**Comment by grechaw** [comment]
I've fixed this issue, in PR later today.

**Comment by bsrikan** [comment]
Verified fix to be working as expected.

**Comment by bsrikan** [comment]
Shipping the issue.
