### ISSUE TITLE
Provide a validation block in schematron for namespace declaration.

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#320]
There are probably valid and invalid uses of namespace and namespacePrefix that I've not uncovered yet.  This issue is to track and implement what we find.

**Comment by grechaw** [comment]
* namespace-uri must be a URI
* prefixes must be unique per namespace-uri

**Comment by bsrikan** [comment]
Verified. Tests will be checked-in after review comments in PR #354 incorporated.

**Comment by bsrikan** [comment]
Test added for this enhancement. Will ship after few runs in regression.

**Comment by bsrikan** [comment]
Test running ok. Shipping the issue.
