### ISSUE TITLE
es:instance-to-envelope() throws XDMP-CHILDNODEKIND error with JSON attachment

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#321]
Query from functional test testInstanceGetAttachmentsJSON()

```
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import module namespace ext = 'http://refSameDocument#Northwind-Ref-Same-Document-0.0.1' at '/conv/valid-ref-same-doc-gen.xqy';

let $sourceDocument := doc('VINET.json')
return xdmp:from-json-string(es:instance-get-attachments(ext:instance-to-envelope(ext:extract-instance-Customer( ($sourceDocument)))))

```

Query returns following error:
`XDMP-CHILDNODEKIND: $attachment -- element nodes cannot have object node children`

**Comment by grechaw** [comment]
Our agreement was that, which this error is acceptable for instance-to-xml-envelope, the legacy function should be backward compatible and quote attachments when needed.

**Comment by bsrikan** [comment]
Thanks for adding that point.

**Comment by grechaw** [comment]
I'll change the description --- pretty sure it's instance-to-envelope throwing the error

**Comment by grechaw** [comment]
Fixing this is a backward incompatibility, but not with any release :)

**Comment by grechaw** [comment]
I've got a fix for this bug.

**Comment by grechaw** [comment]
Now that I've looked back, I need to take my fix back out.  I've put code into both envelope functions that quote attachments -- I think I may just have a little bug int he codegen for canonical xml.  Is your patched version of this module anywhere I can get it -- i want the one with instance-to-canonical xml etc etc

**Comment by bsrikan** [comment]
[valid-ref-same-doc-gen.xqy.zip](https://github.com/marklogic/entity-services/files/1181846/valid-ref-same-doc-gen.xqy.zip)

attached the zip version

**Comment by grechaw** [comment]
I took a look in your module -- I think I need a minor change, but not the change I originally made.  It looks like my intention is to always store attachments without error.  (Which is different from what we discussed yesterday.)  I'm going to shoot an email to the group about this.

**Comment by grechaw** [comment]
come to think of it, I think that it's best if we just don't error out.  

XML envelopes -- quote JSON as string, leave XML alone
JSON envelopes -- quote XML as string, leave JSON alone.

**Comment by kcoleman-marklogic** [comment]
That sounds eminently sensible to me.

**Comment by grechaw** [comment]
OK I have a fix.  Very straightforward it turns out.

**Comment by grechaw** [comment]
Pushing to grechaw/bugfixes, but I'm not going to make a PR until I've looked at a few more of these simple bugs.

**Comment by bsrikan** [comment]
Verified the fix to be working as expected.

**Comment by bsrikan** [comment]
Shipping the issue.
