### ISSUE TITLE
Triples not matching for the unit test testModelXMLConversion()

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#325]
From #324 

> Yes testModelXMLConversion() in the unit tests. I think the issue is currently namespace uri is being output in place of prefixes. Example:
> 
> expected:
> 
> ```
> order:shortKey  a    es:RangeIndexedProperty , es:Property ;
>         es:datatype  xs:short ;
>         es:title     "shortKey" .
>```
> actual:
>```
> <http://marklogic.com/testing-entity-type/SchemaCompleteEntityType-0.0.1/SchemaCompleteEntityType/shortKey>
>         a       <http://marklogic.com/entity-services#RangeIndexedProperty> , <http://marklogic.com/entity-services#Property> , <http://marklogic.com/entity-services#PathRangeIndexedProperty> ;
>         <http://marklogic.com/entity-services#datatype>
>                 <http://www.w3.org/2001/XMLSchema#short> ;
>         <http://marklogic.com/entity-services#title>
>                 "shortKey" .
>```

**Comment by grechaw** [comment]
Hi @bsrikan these two serializations are equivalent, except the second one contains one more triple.
If you change the first line to 

```
order:shortKey  a    es:RangeIndexedProperty , es:Property , es:PathRangeIndexedProperty ;
```

Then the tests will pass, as they check for parsed triples, not serializations.

**Comment by grechaw** [comment]
In PR, ready to go.

**Comment by bsrikan** [comment]
Unit tests are working ok now. Shipping this issue.
