### ISSUE TITLE
Functional test verifySchemaValidation() fails with XDMP-REDCOMPLEXTYPE

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#326]
From #324 

> Functional test verifySchemaValidation() fails with XDMP-REDCOMPLEXTYPE.
> #e68aa52 needs some update as you have mentioned in #322 to the commenting mechanism. Model valid-ref-simple.xml is emitting 2 definitions of:
> 
> ```
> <xs:complexType name="OrderDetailsContainerType">
> <xs:sequence>
> <xs:element ref="OrderDetails">
> </xs:element>
> </xs:sequence>
> <xs:attribute name="datatype">
> </xs:attribute>
> </xs:complexType>
> ```

**Comment by grechaw** [comment]
@bsrikan has a functional test that verifies this issue.

**Comment by grechaw** [comment]
OK I've identified where this bug is.  Tricky.  It occurs because of the method I used to group schemas by namespace.  The model is processed by entity type, and then grouped by namespace, and my duplicate detection is now written at the wrong level.  
The grouping for duplicate detection must be at the namespace level, not the type level

**Comment by grechaw** [comment]
Hi @bsrikan I fixed this issue in PR.  The functional tests still need some work though -- as schema-generate now creates one schema per namespace, you need test mods to load all the generated schemas rather than just one.  I found this tricky enough that I just did it 'manually' for the one type i introduced with multiple namespaces.

**Comment by bsrikan** [comment]
@grechaw I get XDMP-VALIDATEUNEXPECTED error after I load all the generated schemas per namespaces. Can you please look into it.
Attached zip has all the xsd files required to reproduce the issue. You can have all of them in the schemas database at once.
[Namespace-schemas.zip](https://github.com/marklogic/entity-services/files/1247524/Namespace-schemas.zip)
I have 4 instances for model valid-1-namespace.xml and 6 for valid-2-namespace.xml. get-test-instance() works ok.

 The ones that dont work or give validate unexpected error are following.
QUERIES :
```
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "http://marklogic.com/customer" at "valid-1-namespace.xsd";
validate strict { doc('valid-1-namespace-0.xml') } --working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-1-namespace1.xsd";
validate strict { doc('valid-1-namespace-1.xml') } --working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-1-namespace1.xsd";
validate strict { doc('valid-1-namespace-2.xml') } --not working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-1-namespace1.xsd";
validate strict { doc('valid-1-namespace-3.xml') } --not working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-2-namespace.xsd";
validate strict { doc('valid-2-namespace-0.xml') } --working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-2-namespace.xsd";
validate strict { doc('valid-2-namespace-1.xml') } --working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "http://marklogic.com/order" at "valid-2-namespace-ord.xsd";
validate strict { doc('valid-2-namespace-2.xml') } --not working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-2-namespace.xsd";
validate strict { doc('valid-2-namespace-3.xml') } --not working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "http://marklogic.com/super" at "valid-2-namespace-sup.xsd";
validate strict { doc('valid-2-namespace-4.xml') } --not working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-2-namespace.xsd";
validate strict { doc('valid-2-namespace-5.xml') } --working
```

**Comment by bsrikan** [comment]
Model descriptor can be found in functionaltests/src/test/resources/xml-entity-types/
valid-1-namespace.xml and valid-2-namespace.xml and you can probably replace 
`doc('valid-1-namespace-0.xml')` with
`es:model-get-test-instances( es:model-from-xml( fn:doc('valid-1-namespace.xml')))[1]` and so on

**Comment by grechaw** [comment]
Thanks @bsrikan I'll look into it

**Comment by grechaw** [comment]
These two have the same issue:

```

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-1-namespace1.xsd";
validate strict { doc('valid-1-namespace-2.xml') } --not working

import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
import schema "" at "valid-1-namespace1.xsd";
validate strict { doc('valid-1-namespace-3.xml') } --not working
```

As expected, a schema can not be used if the same element name is used for two separate purposes.  In valid-1-namespace, ProductID can refer to the ID of a product, or it can refer to the Product of an OrderDetail.  In the first case we expect an integer, in the second case an embedded or pointer to a Product.

The schema emits the proper comment that flags this situation.  To verify, I renamed OrderDetail/ProductID to OrderDetail/hasProductID and the schemas can be used out of the box.

**Comment by grechaw** [comment]
The other issue is similar. In each case, there names commented out that need to be there in order to work. 
One case does seem fixable.  There is one case where an element name is commented out because it has a duplicate, but only a local name duplicate in a separate schema, so both element names could persist.
I'll see what I can do about this issue.

**Comment by grechaw** [comment]
That wasn't so hard.  It's still an error (and a tricky one) to solve cases like #1, where you really have two properties that mean two different things.

However, I've put in a fix which only wraps duplicates in comments if the duplicate is within the same namespace.

**Comment by grechaw** [comment]
OK this latest commit removes a couple of your 'not working' cases.
I don't have the models ending in -ord or -super so did not persue those.
The issues you have with duplicate names within one namespace should be failures -- there are comments in the schema to explain what's going on.

**Comment by bsrikan** [comment]
While retesting for the fix, I came to know that for generated schema to work or validate as expected we need to remember this:
`schema-gen() generates different xsd per namespace but needs all the xsd that are from one model in the schemas db`
It is better not to have just one xsd in schemas DB, generated from a model having namespace, but all the xsd(s) that such a model generates to avoid errors like:
`XDMP-VALIDATENODECL: XXX in non-lax mode using schema "XXX.xsd"`

We should make note of this in documentation. Subscribing @kcoleman-marklogic

**Comment by bsrikan** [comment]
Verified the issue. Passing over to Kim for documentation as mentioned in my comment above.

**Comment by kcoleman-marklogic** [comment]
@bsrikan Does this cover your concern:

>If your model defines multiple entity types and the entity type definitions do not all use the same namespace, a schema is generated for each unique namespace. Install all of the generated schemas in the modules database.

**Comment by bsrikan** [comment]
Install all of the generated schemas in the `schemas` database, and we are good @kcoleman-marklogic .

**Comment by kcoleman-marklogic** [comment]
Oops, thanks.
