### ISSUE TITLE
es:init-source() doesnt work for json source doc that is not enclosed with a parent

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#328]
After running mldeploy and 'rune2eNwind' for e2e test, I found that envelopes were not getting created for extract-instance-Superstore(). 
After digging a little deeper I found the issue to be with es:init-source(). It has a then statement that looks like 
`    then $source/*`
The extraction works ok if this is `then $source/node()` instead like it was before. '/*' returns the values in json source doc and not the key-value pair, hence the issue.

Sample code to repro the issue:

```
let $source := xdmp:unquote('{"a":"first item", "b":"second item"}')
return  if ( ($source instance of document-node())
        or (exists
            ($source/element()[fn:local-name(.) eq 'Whatever'] )))
    then $source/* 
(: works with /node(). 
    /* would work only if the source looked like xdmp:unquote('{"src": {"a":"first item", "b":"second item"}}')
:)
    else $source
```

**Comment by grechaw** [comment]
You've isolated an issue I knew we had -- this is related to the XPath issues for JSON in TDE.  Needs to be addressed for 9.0-3 for sure.

**Comment by grechaw** [comment]
The object-node JSON document is a special case.  node() doesn't work by itself because for lots of XML documents this will select whitespace text nodes as well as element children.

I need to add a test specifically for this kind of doc, to make sure that all is OK.

**Comment by grechaw** [comment]
I guess a goal of init-source should be to get the top-level non-document node of an input, which should be a single element or an object node.

**Comment by grechaw** [comment]
Well, i was finding this all to be somewhat tricky, but am closing in on a good fix.  Getting all this right also brought to my attention work needed in instance-json-from-document, similar to the bug in #207

**Comment by bsrikan** [comment]
Fix is required to instance-from-doccument(), instance-get-attachments() and instance-xml-from-document() as well like you did for instance-json-from-document().

All these return empty sequence when used with instance-to-json-envelope()

**Comment by grechaw** [comment]
OK.  I'll make a bug for this.

**Comment by grechaw** [comment]
Oh, you just put back to 'fix'.  That's fine, I'll work on this issue to resolve.

**Comment by bsrikan** [comment]
335 is created now to address json-envelope changes to instance-from-doccument(), instance-get-attachments() and instance-xml-from-document(). 
Added a functional test to verify this bug and rune2eNwind also runs fine now. Shipping this issue.
