### ISSUE TITLE
instance-xml-from document not working with JSON envelopes

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#335]
In working on #328 we found that we need new instance handling for JSON envelopes.

This task tracks making unit tests and fixes for each of the instance-X-from-document functions and every envelope type.

**Comment by grechaw** [comment]
I've got instance-xml-from-document working with JSON envelopes.  One minor issue I ran into is that, since JSON envelopes ignore the namespace property, the XML one gets out of JSON envelopes is returned in no namespace.

I think this is OK -- the alternate would be to encode namespaces in JSON documents somehow, which we already decided not to do.

**Comment by bsrikan** [comment]
We are still missing es:instance-get-attachments() for json envelopes I had mentioned in 328 as a comment.

`es:instance-get-attachments(ext:instance-to-envelope(ext:extract-instance-Superstore( doc('namespaceSrc.xml')),"xml"))` works but
`es:instance-get-attachments(ext:instance-to-envelope(ext:extract-instance-Superstore( doc('namespaceSrc.xml')),"json"))` doesnt

**Comment by grechaw** [comment]
ok i was able to repro with a test.  my bad.

**Comment by grechaw** [comment]
OK we're in good shape here with a test and a fix.  back to you

**Comment by bsrikan** [comment]
Test added. Functional tests looking good. Shipping the bug.
