### ISSUE TITLE
create blacklist of prefixes for new namespace-prefix property

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#337]
In 9.0-3, there are no restrictions on the prefixes that developers choose for entity models.

The spec mentions "es", but there are others to avoid, and validation should alert about use of:

"es", "xs", "xml", "xsi", "xsd", "json"

**Comment by grechaw** [comment]
I have implemented this task and updated the specification.   I'll edit the issue to match implementation.

**Comment by bsrikan** [comment]
Tested and have tests ready for checkin. There is an open issue discussed in #354. My tests will be in PR once that is taken care of.

**Comment by bsrikan** [comment]
Test added for this enhancement. Will ship after few runs in regression.

**Comment by bsrikan** [comment]
Test running ok. Shipping the issue.
