### ISSUE TITLE
Change functions {type}:instance-to-canonical($instance) arguments

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#338]
In WG review, we decided to change how to express the API for instance and envelope creation.

This issue is to track updates to spec and to implementation and tests.

instead of

```
instance-to-canonical-xml($instance)
instance-to-canonical-json($instance)
:
```

We introduce a two-argument version of {$type}:instance-to-canonical($instance, $envelope-format)

If the second argument is "json" then a JSON canonical instance is returned.  If it's "xml" then the XML version is returned.

The existing function, retained for backward-compatibility, calls instance-to-envelope($intance, "xml").

**Comment by grechaw** [comment]
This was not a difficult change to do.  I've got it working locally and will prepare a PR this afternoon.

**Comment by bsrikan** [comment]
Verified. Shipping the issue.
