### ISSUE TITLE
Update examples with new codegen

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#339]
The examples which changed in 9.0-3 have been updated with newly generated artifacts.

However, there are examples with no feature-level updates.  These too should have new code generation, even though functionality will not be changed.

**Comment by grechaw** [comment]
I've created one commit that fixes issues with example-person related to namespaces and TDE.  Also moved things around a little bit to align with ml-gradle.

**Comment by grechaw** [comment]
updating races example is somewhat laborious, but I've made some progress this afternoon.

**Comment by bsrikan** [comment]
Updated PR #347 yesterday with issues encountered in person and races example. Some more fix required to this issue. Sending back.

**Comment by grechaw** [comment]
Probably this is OK to ship now.

**Comment by bsrikan** [comment]
Yes it is. Shipping it now.
