### ISSUE TITLE
Investigate use of map:put($namespace) in init-intance

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#340]
@kcoleman-marklogic has noticed that namespace information is added to an instance in two places, both in es:init-instance and in extract-instance-X.  

The first place gets namespace information from scraping the source document.  
In the second its asserted from the model.  The first situation seems wrong to me -- without namespaces information in the model, canonical instances should be written to no namespace regardless of the input XPath and namespaces.

**Comment by grechaw** [comment]
I investigated the two places where namespace information is added.
The use of namespaces in init-instance is currently required for resolving references.  But my hunch remains -- this does not look like the right source for namespace information, but rather might point to having fixed the 'issue' in the wrong place.

**Comment by grechaw** [comment]
I now consider this a more serious issue, which would be great to get fixed.  It's an edge case, but if I address it then the 9.0-3 support for namespaces will be better.  I'm closing in on a good fix but it's a slight API change, so I need to make sure that we're OK with it all around.

The issue is that the method for getting namespace info in init-instance is faulty.  It works for the happy-path extraction. but in some circumstances will result in buggy canonical forms.  I'll include more information in this bug later this evening.

The fix is to have generated code functions pass namespace information to es:init-instance, and to remove the map:with functions from extraction functions.  That solution will make extraction functions cleaner with regard to namespaces, but is a change to the public API at a late point.

Setting to fix.  I'll be aspirational and hope we can get it in.

**Comment by grechaw** [comment]
OK, I've got a fix.  It doesn't look as disruptive as I expected.  I think it's important to go in and I'll circulate for review.

**Comment by grechaw** [comment]
In PR, assigning to you @bsrikan .

**Comment by bsrikan** [comment]
Functional tests have been updated thanks to @grechaw, to reflect latest code change for use of namespaces in init-instance. All green. OK to ship.
