### ISSUE TITLE
Configured namespaces not found in TDE templates

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#341]
It appears that namespace and namespace prefixes, when configured on a type, are not getting implemented with TDE templates.

I suspect that I did this work in a branch that was never merged in, as it's a surprising gap.

In TDE, both path namespaces and all XPaths needs to be in the right namespace

**Comment by grechaw** [comment]
Started work on this issue, but I'm slightly mired down.  I need to make some assertions for a simpler namespaced model, then tackle SchemaCompleteEntityType for a more complex look.

**Comment by grechaw** [comment]
All tests now passing, will add fix and tests to PR.

**Comment by bsrikan** [comment]
Shipping the issue as the tests are running ok in regression. Configured namespaces are now available in the generated TDE.
