### ISSUE TITLE
Version translator code has an improper closing braces in a commented out code

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#349]
For scenarios similar to an entity type in source but not in target model, the commented out code has a closing brace } instead of bracket )

Example:
   ` =>map:with("$type", "ShipDetails" }
`
should be 
    `=>map:with("$type", "ShipDetails" )`

**Comment by grechaw** [comment]
Given this is in comments, it doesn't seem unreasonable to expect it go get into the release.

**Comment by grechaw** [comment]
This will be in a PR with #351 in a minute or two.

**Comment by bsrikan** [comment]
Test in e2e and functional tests verified this bug and is working as expected. Shipping.
