### ISSUE TITLE
Syntax error in version translate for property that is an internal reference

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#351]
For a property say "hasCustomerID" that is an internal ref in model2, version translator produces a syntax error on deploying the artifact.

Model1:
```
 "hasProductID":{  
               "datatype":"integer"
            }
```

Model2:
```
"hasCustomerID": {
          "$ref": "#/definitions/Customer"
        }
```

Code in version translator that produces syntax err:
```
let $hasCustomerID := $source-node/hasCustomerID ! es:init-instance(?, 'Customer')
=>es:with-namespace('http://marklogic.com/customer','cust')(.)
```

expected:
`let $hasCustomerID := $source-node/hasCustomerID ! $extract-reference-Customer(.)`

**Comment by grechaw** [comment]
I'm in this code right now fixing issue #349 so I'll try to get it snuck in at this late stage.  Not good to ship a syntax error.

**Comment by grechaw** [comment]
I see now why I hit this error.  the partial function is not composable with the es:with-namespace expression in the way I would have expected.  interesting.  I need to look more closely at your expected value though...

**Comment by bsrikan** [comment]
Ok. I mentioned it so, since that version worked for me. But you are right, please check for other scenarios too.

**Comment by grechaw** [comment]
This particular property is hitting the 'reference from scalar' logic.  The expected value needs to be its own function, which could go in a variable or inline.  Here's the inline version:

```

    let $hasCustomerID := $source-node/hasCustomerID ! function($src-node) {
       es:init-instance($src-node, 'Customer')
       =>es:with-namespace('http://y','y')}(.)
```

**Comment by bsrikan** [comment]
Test in e2e verified this bug and is working as expected. Shipping.
