### ISSUE TITLE
Version translator is missing a scenario for namespaces

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#352]
When working with upconverts I saw that a query like 
`new:instance-to-envelope(t:convert-instance-X(doc(‘envelope-from-model1’))) `
doesn’t preserve namespace present in model2.
It will be good to have a logic for version translate when it comes to scenario like source has namespace, target doesn’t and vice versa.

**Comment by bsrikan** [comment]
@grechaw today is functional complete day for 9.0-4. Will this be available for test today or latest by Monday. Please let me know.

**Comment by grechaw** [comment]
I won't be able to deliver by today, no.   Monday is a bit of a stretch given how full it is down at San Carlos, but I will focus some hours on it this weekend and let you know how it goes.

**Comment by bsrikan** [comment]
Working on e2e updates for this bug. Will have a PR in a day or 2.

**Comment by bsrikan** [comment]
I have three scenarios to test this with:

Case1: source has no namespace; target has namespace for that ET
Case2: source has an ET with namespace; target doesnt have namespace for that ET
Case3: source has an ET with namespace; target has a new namespace for that ET

What should the convert instance look like for each of the three.
For Case1, convert-instance() has es:with-namespace() as expected
For Case2, convert-instance() has no es:with-namespace() as expected. Although I think we should include es:with-namespace() and comment it out, like other properties 
For Case3: convert-instance() has es:with-namespace() same as source. Doesnt take namespace of the target

We did not have a spec update for this bug. Might be a good thing to have now, with these scenarios. Let me know what do you think the behavior should be.

Sending it back to you for review.

**Comment by grechaw** [comment]
OK, I'll make sure this info gets into the spec.  It didn't feel like I came up with a lot of questions in my implementation, so I think it's all pretty straightforward.

**Comment by bsrikan** [comment]
Got clarified after discussing with Charles that XPath expressions in the let statements of convert-instance() block will have namespace of source model. Hence it is expected.

I have updated my tests and they work fine.

**Comment by bsrikan** [comment]
Tests running OK in regression. Shipping the issue.
