### ISSUE TITLE
A model with duplicate namespace URI but unique prefix should throw an error

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#355]
Run model-validate() on an xml/json model with duplicate namespace URI but unique prefix.
This should throw an error. Current implementation wont it seems apparently.

Issue created from test case(107) review of 9.0-4 test plan.

**Comment by grechaw** [comment]
well, that was quick.

**Comment by bsrikan** [comment]
Now we get an error, but the logic has false positives and false negatives as commented in #354 .
Will ship once that is fixed.

**Comment by bsrikan** [comment]
Added test that verifies this fix. Good to ship.

**Comment by bsrikan** [comment]
Test running ok. Shipping the issue.
