### ISSUE TITLE
instance-to-canonical-xml converting an array

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic/entity-services#375]
I was wondering if there is any reason for adding attribute `datatype="array"` when we are canonicalizing an array of json objects or strings. The reason I ask is for eg: if my json that I am trying to canonicalize has the structure as follows
```
{
	"companies": [{
		"name": "Florida Hospital Transplant Center",
		"id": "1075673",
		"type": "Sponsor"
	},
	{
		"name": "Genzyme Ltd",
		"id": "16300",
		"type": "Collaborator"
	},
	{
		"name": "Novartis AG",
		"id": "23137",
		"type": "Collaborator"
	}]
}
```
the resulting xml looks likes follows:

```
<companies datatype="array">
  <company>
    <name>Florida Hospital Transplant Center</name>
    <id>1075673</id>
    <type>Sponsor</type>
  </company>
</companies>
<companies datatype="array">
  <company>
    <name>Genzyme Ltd</name>
    <id>16300</id>
    <type>Collaborator</type>
  <company>
</companies>
<companies datatype="array">
  <company>
    <name>Novartis AG</name>
    <id>23137</id>
    <type>Collaborator</type>
  </company>
</companies>
```

I could modify the code generated by es to have all the `<company>` elements inside the `<companies>` or remove the `<companies>` tag completely.. but I was wondering about the significance of datatype as is this used for any TDE generations ?

**Comment by grechaw** [comment]
I see two questions here

1.  the canonical structure here has a property "companies" and a type "company".  We recommend that you use a property that has semantic meaning for the relationship, like "worksFor" or "soldTo", and then use uppercase for the embedded type, Company.  Having a property and a type that are semantically equivalent is collapsing two concepts in entity services.

2. the attribute is used just to help with serialization back to JSON.   In XML, a sequence of one is indistinguishable for a single item.  So in the case there there's just one item in an array, the datatype attribute assists in serialization.  It was a little ugly but kept serialization from needing to query the model.

The nesting is important for generation of TDE. If you change it, then you'll also have to change the generated code.  You're welcome to do so, but you'll be breaking how entity services works OOTB.

**Comment by ravi-b-m** [comment]
If I change the canonicalization to the following, will this effect the TDE
```
<companies datatype="array">
  <company>
    <name>Florida Hospital Transplant Center</name>
    <id>1075673</id>
    <type>Sponsor</type>
  </company>
  <company>
    <name>Genzyme Ltd</name>
    <id>16300</id>
    <type>Collaborator</type>
  <company>
  <company>
    <name>Novartis AG</name>
    <id>23137</id>
    <type>Collaborator</type>
  </company>
</companies>
```
Will namespace be any issue, for eg:= `<companies>` is in different namespace than `<company>` ?

**Comment by grechaw** [comment]
It is possible to declare namespaces for your XML serializations if you choose.  That's in the model, ad the entity type level.

This particular change will not affect the TDE, since the XPaths for any given node remain the same.

**Comment by grechaw** [comment]
Thanks for the interaction, @ravi-b-m
