### ISSUE TITLE
Issue to test bugtrack integration.

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#45]
This is a test.

**Comment by rashiatmarklogic** [comment]
great was thinking to do this too. Lets see if this gets created in bugtrack in like 6 hrs or so.. I do not see entity-services category in bugtrack though.

**Comment by grechaw** [comment]
Hi @rashiatmarklogic .  This issue was imported here  https://bugtrack.marklogic.com/39976

I updated labels in this project to work like some of the other ones we have.  You need 'Bug', a status and a severity label to make the integration work.  

I'll update the milestones to match what bugtrack expects - -maybe the reporting will just work out.  Sudhakar should change the category to "Entity Services" so we'll see them together.

**Comment by grechaw** [comment]
Changed status to watch integration work.
