### ISSUE TITLE
Error when running xquery to transform each document in the raw collection

### ISSUE THREAD

**Issue by sastafford** [marklogic/entity-services#46]
I'm following the tutorial for Entity Services on the EA website.  I'm at the part where I need to run the transform on all the documents on the raw collection and I get the following error in QConsole.  

[1.0-ml] XDMP-CHILDNODEKIND: map:get($entity-instance, "$attachments") -- element nodes cannot have object node children
Stack Trace

In /ext/Race-0.0.1.xqy on line 216
In race:instance-to-envelope(json:object(<json:object xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:json="http://marklogic.com/xdmp/json"><json:entry key="$type"><json:value xsi:type="xs:string">Run</js...</json:object>))
$entity-instance := json:object(<json:object xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:json="http://marklogic.com/xdmp/json"><json:entry key="$type"><json:value xsi:type="xs:string">Run</js...</json:object>)

**Comment by sastafford** [comment]
It doesn't like XML Constructor around the JSON map for element es:attachments 

```XQuery
declare function race:instance-to-envelope(
    $entity-instance as map:map
) as document-node()
{
    document {
        element es:envelope {
            element es:instance {
                element es:info {
                    element es:title { "Race" },
                    element es:version { "0.0.1" }
                },
                race:instance-to-canonical-xml($entity-instance)
            },
            element es:attachments {
                map:get($entity-instance, "$attachments") 
            }
        }
    }
};
```

**Comment by grechaw** [comment]
Hi @sastafford that is correct -- our initial foray just uses XML for an envelope.  In your extraction module, you must customize the line that puts $attachments to hold a xdmp:quoted version.

I've been mulling over whether this is a common enough use case to go ahead and implement JSON envelopes for those who with to use them..

**Comment by grechaw** [comment]
Hi @jmakeig this issue is an RFE.  We know it would be pretty straightforward to make JSON envelopes.  It will just take a little research to see what is and isn't supported by such an envelope.
Note that there's an instance function to get JSON out of an XML envelope -- the disadvantage with the current limitation is that you cannot store JSON sources as attatchments without quoting them.

**Comment by grechaw** [comment]
@paxtonhare created #144 to explicitly ask for a JSON envelope.  That would solve this issue as well, so I'll close this as a duplicate.
