### ISSUE TITLE
Instance envelopes use es:title from the document, not the type of the instance

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#52]
I discovered this bug while implementing search options.  

When you use a conversion modules's conv:instance-to-envelope() function, the envelope has a

es:title element with the value of the document's title.  This title is supposed to indicate the type of the entity instance, and so should be a type name not the document name.

I've got a fix prepared.

**Comment by grechaw** [comment]
Hi @rashiatmarklogic @bsrikan I wanted to alert you to this bug, as it will change conversion module code when it goes into develop.  The change is in the es:instance-to-envelope function (and is obvious from the commit)

**Comment by rashiatmarklogic** [comment]
Noted. You can merge the change to develop and we will handle the regression.

**Comment by rashiatmarklogic** [comment]
I think that TestEsConversionModuleGenerate.java is failing in regression today because of this change.

**Comment by bsrikan** [comment]
Shipping this in git as Rashi already shipped the one in Bugtrack -- 40431.
