### ISSUE TITLE
Change in element order for schema-generate

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#68]
When I committed 6b9ed50dc70533 for bug 40598, I also changed the order of elements in the schema-generate to be more sensible.  This issue is to track that change for testing.  There's no functional change for schemas, in that commit, just the ordering of elements.

**Comment by bsrikan** [comment]
Rashi shipped this bug in Bugtrack. Hence shipping it in git..

TestEsRequired.java and TestEsSchemaGenerator.java are verifying this bug, and they are passing now. Good to ship !
