### ISSUE TITLE
ValidateUnexpected and ValidateBadType schema errors for some instances of an ET doc that include $ref

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#71]
1> Using schema valid-ref-same-document.xsd
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
validate strict { doc ('valid-ref-same-document-2.xml')}

Error msg:
[1.0-ml] XDMP-VALIDATEBADTYPE: (err:XQDY0027) validate strict { fn:doc("valid-ref-same-document-2.xml") } -- Invalid node type: ProductID lexical value "" invalid for expected type #xs:integer at fn:doc("valid-ref-same-document-2.xml")/Order/OrderDetails[1]/OrderDetail/ProductID using schema "valid-ref-same-document.xsd"

2> Using schema valid-ref-same-document.xsd
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
validate strict { doc ('valid-ref-same-document-3.xml')}

Error msg:
[1.0-ml] XDMP-VALIDATEUNEXPECTED: (err:XQDY0027) validate strict { fn:doc("valid-ref-same-document-3.xml") } -- Invalid node: Found Product but expected #xs:integer at fn:doc("valid-ref-same-document-3.xml")/OrderDetail/ProductID/Product using schema "valid-ref-same-document.xsd"

3> Using schema valid-ref-combo-sameDocument-subIri.xsd
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
validate strict { doc ('valid-ref-combo-sameDocument-subIri-3.xml')}

Error msg:
[1.0-ml] XDMP-VALIDATEUNEXPECTED: (err:XQDY0027) validate strict { fn:doc("valid-ref-combo-sameDocument-subIri-3.xml") } -- Invalid node: Found Product but expected #xs:integer at fn:doc("valid-ref-combo-sameDocument-subIri-3.xml")/OrderDetail/ProductID/Product using schema "valid-ref-combo-sameDocument-subIri.xsd"

4> Using schema valid-simple-ref.xsd
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
validate strict { doc ('valid-simple-ref-2.xml')}
Same for -0 and -1

Error msg:
[1.0-ml] XDMP-VALIDATEBADSCHEMA: validate strict { fn:doc("valid-simple-ref-2.xml") } -- Invalid schema "" at "valid-simple-ref.xsd": valid-simple-ref.xsd

**Comment by grechaw** [comment]
Hi @bsrikan  there is a bug in the TestEsSchemaGeneation teardown.  I fixed the same bug in unit tests last week.

```
@AfterClass
	public static void cleanupSchemas() {
		for (String entityType : schemas.keySet()) {

			String moduleName = "/ext/" + entityType.replaceAll("\\.(xml|json)", ".xsd");

			docMgr.delete(moduleName);
		}
	}
```

The /ext/ should not be there in the 'moduleName' line.  just look at schema unit tests for how cleanup should look.

**Comment by bsrikan** [comment]
True Charles. Removing /ext/ will help cleaning up stored schema files. Other issue mentioned here is for XDMP-VALIDATEUNEXPECTED which requires a fix. Please take a look.

**Comment by bsrikan** [comment]
Infact all 4 errors mentioned are reproduced even after taking care of cleaning up by removing /ext/

**Comment by grechaw** [comment]
OK thanks for the additional info.  I'll try to reproduce.

**Comment by grechaw** [comment]
This issue may be fixed as part of my current work on references.

**Comment by grechaw** [comment]
I now indeed recognize this behavior and now have tests and code to cover it.  Setting to Fix, expect to be referenced in PR shortly

**Comment by grechaw** [comment]
I'm taking a look at the cases here to determine where there may or may not be a bug.

1> Using schema valid-ref-same-document.xsd
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
validate strict { doc ('valid-ref-same-document-2.xml')}

* not a bug.
The model for the ProductID property has it as an integer, and optional.  
The document you're validating has <ProductID/> as an empty element.  The schema will validate a document that is *missing* the <ProductID/> element, but if it's there, in order to be valid, it must contain an integer.  

So these both validate

```xml
<Order>
<OrderID>123</OrderID>
<CustomerID>123</CustomerID>
<OrderDate>2000-01-23T17:00:26.789186-08:00</OrderDate>
<ShipAddress>some string</ShipAddress>
<OrderDetails>
<OrderDetail>
<UnitPrice>123</UnitPrice>
<Quantity>123</Quantity>
</OrderDetail>
</OrderDetails>
<OrderDetails>
<OrderDetail>
<UnitPrice>123</UnitPrice>
<Quantity>123</Quantity>
</OrderDetail>
</OrderDetails>
<OrderDetails>
<OrderDetail>
<UnitPrice>123</UnitPrice>
<Quantity>123</Quantity>
</OrderDetail>
</OrderDetails>
</Order>
```

or 

```
<Order>
<OrderID>123</OrderID>
<CustomerID>123</CustomerID>
<OrderDate>2000-01-23T17:00:26.789186-08:00</OrderDate>
<ShipAddress>some string</ShipAddress>
<OrderDetails>
<OrderDetail>
<ProductID>123</ProductID>
<UnitPrice>123</UnitPrice>
<Quantity>123</Quantity>
</OrderDetail>
</OrderDetails>
<OrderDetails>
<OrderDetail>
<ProductID>123</ProductID>
<UnitPrice>123</UnitPrice>
<Quantity>123</Quantity>
</OrderDetail>
</OrderDetails>
<OrderDetails>
<OrderDetail>
<ProductID>123</ProductID>
<UnitPrice>123</UnitPrice>
<Quantity>123</Quantity>
</OrderDetail>
</OrderDetails>
</Order>
```
HOWEVER, since ProductID appears several times in the schema, you'll see that there are a few declarations commented out:

```
<!--
This item is a duplicate and is commented out so as to create a valid artifact.
 <xs:element name="ProductID" type="ProductContainerType" xmlns:xs="http://www.w3.org/2001/XMLSchema"/> 
-->
```

If you're using embedded Products, then this would be the right schema def to use, not the one that's in there by default.

**Comment by grechaw** [comment]
One thing that might be at play here is that es:entity-type-get-test-instances() has changed with regard to external references.  We might want to review the test cases to see which ones are valid.

**Comment by grechaw** [comment]
Case 2 requires the commented-out ProductID definition to be the one in use.   So case 2 is a kind of customization case, which shows the alternatives that must be taken if one has multiple ways to reference one property in a model.

**Comment by grechaw** [comment]
Case 3 looks the same as case 2.

**Comment by grechaw** [comment]
Case 4 looks like it's still an issue:

```
import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';


let $pathname := "/MarkLogic/git/entity-services/entity-services-functionaltests/src/test/resources/json-entity-types/valid-simple-ref.json"
let $et := xdmp:filesystem-file($pathname)=>xdmp:unquote()=>es:entity-type-from-node()
let $schema := es:schema-generate($et)

return validate { $schema }

```

**Comment by grechaw** [comment]
Ah I understand case 4 -- it's because there's a local and external reference with the same local name -- I have to account for this situation.

**Comment by grechaw** [comment]
Aha!  It's because you have a property name that is equal to an entity type name.

Best practice will be to lowercase property names and capitalize type names, so this is an edge case.  

I think that this is bad enough practice that we should catch it in validation and disallow.

**Comment by grechaw** [comment]
Oh, @bsrikan if you put 'fixes xxx' into a commit it closes an issue.  This breaks bugtrack integration :)
Reopening so that it will be assigned properly in BT

**Comment by bsrikan** [comment]
Oh! I read that '#xxx' doesnt close the issue. But I added fixes in my statement that closed the issue I think. Will be careful.

**Comment by bsrikan** [comment]
Added new model and updated test to validate Entity and property names are distinct

**Comment by bsrikan** [comment]
There were changes made to schema gen and how model-get-test-instances() behave for references. Type was added per #77. 
The errors reported in this bug are understood and work as expected when the OOTB generated schema is edited to uncomment the needed elements which were otherwise commented as duplicates.
Test for the validation enforced has been running in regression after merge of #100.
Hence good to ship this bug as the issue in the bug has to be handled with manual intervention and changing the generated schema.
