### ISSUE TITLE
external references should have the type as an enclosing element name.

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#77]
The canonical representation of an embedded entity instance wraps the outer structure within each property element.  It should look more like this, whereas now the type information of reference is lost unless the instance is embedded.  This is really a design and implementation bug and I'm addressing it in the specification as I submit this issue to track its execution.

Also, existing bug 40487 requests clarification on external references -- this issue will help to resolve that one.

```
{
  "$type": "NameOfEntityType",
  "property1":"value1",
  "property2": [ 1, 2, 3 ],
  "embeddedReference": { 
    "$type":"NameOfEntityType",
    "p1":"v1",...
  },
  "embeddedArrayReference": [
  { 
    "$type":"NameOfEntityType",
    "p1":"v1",...
  },
  { 
    "$type":"NameOfEntityType",
    "p1":"v1",...
  },
  { 
    "$type":"NameOfEntityType",
    "p1":"v1",...
  }],
  "externalReference":
    {"$type":"NameOfEntityType",
     "$ref": ..value..
    },
  "externalArrayReference": [
    {"$type":"NameOfEntityType",
     "$ref": ..value..
    },
    {"$type":"NameOfEntityType",
     "$ref": ..value..
    },
    {"$type":"NameOfEntityType",
     "$ref": ..value..
    }
    ]
```

**Comment by grechaw** [comment]
Also related to bug:39341

**Comment by grechaw** [comment]
I'm knocking this bug out now -- it will require several key updates.

I need to have this right in order to implement version comparisons properly

**Comment by grechaw** [comment]
Significant progress on this bug today.

**Comment by grechaw** [comment]
I'm working though a schema validation consequence of my change, and will have a PR before noon on this.  completing version comparison may well follow in the afternoon.

**Comment by bsrikan** [comment]
Fixed regression tests and created PR #86

**Comment by grechaw** [comment]
This issue was a kind of forced design update, and upon reflection I think there are bugs in
database-properties-generate and extraction-templates.  When working with examples I realized that I had to change an extraction template when there was  reference involved.  

I'll make a stub issue for investigation.

**Comment by bsrikan** [comment]
This bug is also good to ship as the extract-instance tests were updated accordingly going with current output as the expected. Will reopen in EA-4 if required.
