### ISSUE TITLE
Investigate the special case of serialization entity instance to JSON, with array of  one item

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#80]
When an entity instance stores a propery, it uses XML elements and sequence semantics to do so.  That means that the instance data model cannot tell when it is representing an array, if there is only one item in the array.

We need to investigate this issue and perhaps correct it.  An attribute in the XML data could solve the issue.

**Comment by grechaw** [comment]
I've got an implementation of this working.  I'll pitch it to the WG Monday and see whether or not to move foward with the change.

In essence, I've added an attribute to the default for `es:instance-to-canonical-xml`.  If a property is of type array, then the XML has an attribute datatype="array" added to it

```
<Order>
    <orderId>10248</orderId>
    <orderDate>1995-07-05</orderDate>
    <hasOrderDetails datatype="array">
        <OrderDetails>
            <quantity>40</quantity>
            <productName>Capris</productName>
        </OrderDetails>
    </hasOrderDetails>
</Order>
```

This attribute can inform es:instance-json-from-document(), which then serializes this item property as an array rather than as a single item.

Up to this point we do not have a way to ensure that the output in JSON has an array.

Should work for empty arrays too, for required properties.

```
<Order>
    <orderId>10248</orderId>
    <orderDate>1995-07-05</orderDate>
    <hasOrderDetails datatype="array" />
</Order>
```

**Comment by bsrikan** [comment]
Shipping the bug as the added tests run OK in regression.
