### ISSUE TITLE
Refactor names of signatures and functions to be 'model' where now is implied e-t-doc

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#82]
We have a loosey-goosey notion of an entity services document.  To clarify the role of the in-memory model in the API, we'll change some functions.  The WG approved the changes today, and the spec reflects some of them already.  This issue will trace the implementation.

**Comment by grechaw** [comment]
subtask:  change name of collection in TDEs.
subtask:  change name of element in schema
subtask:  testing name updates
subtask:  function signatures
subtask: examples, including QC workspace

**Comment by grechaw** [comment]
I've done the implementation and tests are all passing.
Still to finish:  examples, verify spec.
I'll make another commit to clean up names throughout, without changing functions or keys.  Then I'll make a PR for @rashiatmarklogic  and @bsrikan  to consider.

**Comment by grechaw** [comment]
This issue is in PR - will be merged today and assigned to @bsrikan

**Comment by bsrikan** [comment]
Great

**Comment by bsrikan** [comment]
Tests are running successfully in regression after absorbing the change in function signatures and error msgs from "entity-type" to "model".

**Comment by bsrikan** [comment]
This bug is validated through tests running in regression. Good to ship.
