### ISSUE TITLE
configuration of ml-schemas needs solution for examples

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#85]
The subproject entity-services-examples currently configures its mlSchemasPath 
in `entity-services-examples/gradle.properties` as "mlSchemasPath=entity-services-examples/src/main/ml-schemas" which allows the parent project to deploy using

`./gradlew entity-services-examples:mlDeploy`

however, from within the child directory, 

`./gradlew mlDeploy` does not read the schemas from the local project.

I need to understand the proper way to configure this path.

**Comment by grechaw** [comment]
The PR for examples right now works from IDEs and from the command line from within
entity-services-examples, which I think is preferable to the previous method, which only worked 
from the parent project.

**Comment by bsrikan** [comment]
Sure Charles.
e2e folder works the same way I think. It has its path configured as src/main/ml-schemas.
Can you show in our meeting tomorrow the problems/difficulties faced with the path having entity-services-examples in it by comparing these 2.

**Comment by grechaw** [comment]
Sure thing

**Comment by grechaw** [comment]
We agreed to move forward with the fix as represented in the examples PR.  I'll push this issue through when we decide to merge examples.

**Comment by grechaw** [comment]
This is all done and set.  Will be mergen when the examples are.

**Comment by bsrikan** [comment]
Examples project is now setup such that mldeploy should be run from examples dir. Will ship after successful regression run.

**Comment by bsrikan** [comment]
Shipping the bug as the unit/functional tests and examples/e2e artifacts are running/deployed successfully in regression.
