### ISSUE TITLE
Check extraction templates and range index defs (paths) for references

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#91]
Issue #77 changed somewhat how we expect to persist references.  While the change caused issues and fixes for schema generation, I suspect a bug in extraction templates now.

This issue is to investigate and track what's next.

Put EA-3 to verify.  Not sure whether I need to fix this or not, but I think it does need a fix.

Now, a reference's index will be defined the same as if it were a scalar property.  It needs an additional step for entity type.

is: <property>value</property>    /property
should be <property><Type>value</Type></property>   /property/Type

**Comment by grechaw** [comment]
I've got a fix for this issue.  It corrects extraction template generation so as to get paths to references correct.

**Comment by grechaw** [comment]
This is about the embedded references in #77 -- I missed needed changes in extraction template.

**Comment by bsrikan** [comment]
This bug is validated through tests running in regression. As a result of this bugfix, there were key changes required for extract instances test in TestEsConversionModuleGenerator.java and were pushed to develop via #105. Good to ship.
