### ISSUE TITLE
ES-MODEL-INVALID : Local reference #/definitions/OrderDetail

### ISSUE THREAD

**Issue by rashiatmarklogic** [marklogic/entity-services#93]
must resolve to local entity type.Local reference #/defintions/Product must resolve to local entity type.

The XQuery
==========
  xquery version "1.0-ml";
  import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
  es:extraction-template-generate( es:model-from-node( fn:doc("valid-ref-same-document.xml")))

The model looks like : 
================

```
{  
   "info":{  
      "title":"Northwind-Ref-Same-Document",
      "version":"0.0.1",
      "baseUri":"http://refSameDocument"
   },
   "definitions":{  
      "Customer":{  
         "properties":{  
            "CustomerId":{  
               "datatype":"string"
            },
            "CompanyName":{  
               "datatype":"string"
            },
            "Country":{  
               "datatype":"string"
            },
            "Address":{  
               "datatype":"string"
            }
         },
         "primaryKey":"CustomerId",
         "required": ["CustomerId"]
      },
      "Product":{  
         "properties":{  
            "ProductName":{  
               "datatype":"string"
            },
            "ProductID":{  
               "datatype":"integer"
            },
            "UnitPrice":{  
               "datatype":"integer"
            },
            "SupplierID":{  
               "datatype":"integer"
            },
            "Discontinued":{  
               "datatype":"boolean"
            }
         }
      },
      "Order":{  
         "properties":{  
            "OrderID":{  
               "datatype":"integer"
            },
            "CustomerID":{  
               "datatype":"integer"
            },
            "OrderDate":{  
               "datatype":"dateTime"
            },
            "ShipAddress":{  
               "datatype":"string"
            },
            "OrderDetails":{  
               "datatype":"array",
               "items":{  
                  "$ref":"#/definitions/OrderDetail"
               }
            }
         }
      },
      "OrderDetail":{  
         "properties":{  
            "ProductID":{  
               "$ref":"#/definitions/Product"
            },
            "UnitPrice":{  
               "datatype":"integer"
            },
            "Quantity":{  
               "datatype":"integer"
            }
         }
      }
   }
}
```

Please note the above error ES-MODEL-INVALID is only seen when I am passing XML version of the model.With the JSON version of the model I do not see this error.

**Comment by rashiatmarklogic** [comment]
@bsrikan : Hi Srikanth subscribing you in this issue as well. Please note that its only happening ( I think) when we pass a XML version of the model 
es:extraction-template-generate( es:model-from-node( fn:doc("valid-ref-same-document.xml")));

Since, 
es:extraction-template-generate( es:model-from-node( fn:doc("valid-ref-same-document.json")));
works fine. 

I am not sure that which bug might have introduced this issue, Friday 07/22 when the name changes were not in this test passed without issues. TestEsExtractionTemplate.java

**Comment by rashiatmarklogic** [comment]
Same issue seen with es:model-get-test-instances() API and TestEsInstanceGenerator.java

Xquery
======
  xquery version "1.0-ml";
  import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
  es:model-get-test-instances( es:model-from-node( fn:doc("valid-ref-same-document.xml")))

And the XQuery2
=============

  xquery version "1.0-ml";
  import module namespace es = 'http://marklogic.com/entity-services' at '/MarkLogic/entity-services/entity-services.xqy';
  es:model-get-test-instances( es:model-from-node( fn:doc("valid-ref-same-document.json")))

works just fine.

**Comment by rashiatmarklogic** [comment]
I am marking this issue as critical - reason is that its actually blocking QA to test anything further. Many test cases are hitting same issue and failing in regression. 

Charles - Please solve this issue ASAP.

**Comment by grechaw** [comment]
I'll try to reproduce now

**Comment by grechaw** [comment]
One of the changes from issue #82 was that 'es:entity-type' is now called 'es:model'

All of the XML models must be updated.

**Comment by grechaw** [comment]
So probably PR #94 has the fix to this issue too?  I saw that a lot of the elements had that renaming.

**Comment by rashiatmarklogic** [comment]
Yes, thats true #94 has a fix for this.
